services:
  - type: web
    name: killer-sudoku
    env: static
    buildCommand: npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /privacy-policy
        destination: /index.html
      - type: rewrite
        source: /terms-of-service
        destination: /index.html
      - type: rewrite
        source: /cookie-policy
        destination: /index.html
      - type: rewrite
        source: /contact
        destination: /index.html
      - type: rewrite
        source: /*
        destination: /index.html

