import { useState, useEffect } from 'react';
import { Language } from '@/components/LanguageToggle';

// 語言翻譯對象
const translations = {
  en: {
    // 遊戲相關
    gameTitle: 'Sudoku',
    newGame: 'New Game',
    gameRules: 'Game Rules',
    difficulty: 'Difficulty',
    easy: 'Easy',
    medium: 'Medium',
    hard: 'Hard',
    expert: 'Expert',
    hell: 'Hell',
    
    // 多巴胺模式
    dopamineMode: 'Dopamine Mode',
    startChallenge: 'Start Challenge',
    remaining: 'Remaining',
    score: 'Score',
    combo: 'COMBO',
    
    // 註解功能
    showNotes: 'Show Notes',
    hideNotes: 'Hide Notes',
    notes: 'Notes',
    notesOn: 'Notes ON',
    notesOff: 'Notes OFF',
    notesModeOn: 'Enable Notes Mode',
    notesModeOff: 'Disable Notes Mode',
    candidateNumbers: 'Candidate Numbers',
    
    // 多巴胺資訊卡
    dopamineInfoTitle: 'Dopamine Mode',
    dopamineInfoSubtitle: 'Challenge Your Limits!',
    dopamineFeatures: 'Mode Features',
    dopamineRules: 'Game Rules',
    basicAchievement: 'Basic Achievement',
    moderateChallenge: 'Moderate Challenge',
    highAchievement: 'High Achievement',
    topChallenge: 'Top Challenge',
    highestAchievement: 'Highest Achievement',
    selectDifficulty: 'Select Difficulty',
    startDopamineChallenge: 'Start Challenge',
    challengeYourLimits: 'Challenge Your Limits',
    userLimited: 'User Limited',
    beyondNormalMode: 'Beyond Normal Mode',
    modeFeatures: 'Mode Features',
    selectChallengeDifficulty: 'Select Challenge Difficulty',
    chooseDifficultyChallenge: 'Choose difficulty challenge, focus on specific difficulty',
    specialScoringSystem: 'Special scoring system, combo and speed rewards',
    timeLimitChallenge: 'Complete sudoku challenge within time limit',
    errorCountAffectsScore: 'Error count affects final score',
    consecutiveCorrectReward: 'Consecutive correct filling can get combo reward',
    speedCompletionBonus: 'Faster completion gives higher score bonus',
    challengeFailed: 'Challenge Failed',
    dopamineAchievementWall: 'Dopamine Achievement Wall',
    noTopScoreData: 'No Top Score Data',
    difficultyLevel: 'Difficulty Level',
    againChallenge: 'Challenge Again',
    returnToMainMenu: 'Return to Main Menu',
    congratulationsComplete: 'Congratulations Complete',
    successfullyCompletedGame: 'You have successfully completed the game',
    currentRank: 'Current Rank',
    totalScore: 'Total Score',
    newRecord: 'New Record!',
    completionTime: 'Completion Time',
    errorCount: 'Error Count',
    playAgain: 'Play Again',
    viewLeaderboardButton: 'View Leaderboard',
    congratulations: 'Congratulations',
    remainingTime: 'Remaining Time',
    maxCombo: 'Max Combo',
    
    // 排行榜
    leaderboard: 'Leaderboard',
    viewLeaderboard: 'View Leaderboard',
    viewHighestScore: 'View Highest Score',
    all: 'All',
    gamesPlayed: 'Games Played',
    achievementWall: 'Achievement Wall',
    noData: 'No Data',
    highestScoreDisplay: 'Highest Score Display',
    
    // 用戶相關
    welcome: 'Welcome',
    welcomeToKillerSudoku: 'Welcome to Sudoku',
    enterNameToStart: 'Please enter your name to start playing and participate in the leaderboard',
    enterYourName: 'Please enter your name',
    processing: 'Processing...',
    startGame: 'Start Game',
    visitorMode: 'Visitor Mode',
    visitorModeDescription: 'Visitor mode does not score and does not participate in leaderboard',
    checkNetworkConnection: 'Please check your network connection or try again later. If the problem persists, please contact the administrator.',
    usernameAlreadyExists: 'Username already exists, please enter a different name',
    viewStats: 'View Stats',
    normal: 'Normal',
    dopamine: 'Dopamine',
    
    // 通用
    close: 'Close',
    back: 'Back',
    restart: 'Restart',
    returnToMain: 'Return to Main Menu',
    clear: 'Clear',
    
    // 主題
    currentTheme: 'Current theme',
    clickToToggle: 'Click to toggle between light and dark',
    
    // 載入狀態
    loadingStats: 'Loading stats...',
    
    // 用戶統計
    bestScore: 'Best Score',
    bestTime: 'Best Time',
    totalGames: 'Total Games',
    
    // 遊戲規則
    scoringSystem: 'Scoring System',
    rules: 'Rules',
    scoring: 'Scoring',
    tips: 'Tips',
    basicRules: 'Basic Rules',
    killerSudokuFeatures: 'Killer Sudoku Features',
    solvingStrategy: 'Solving Strategy',
    uniqueCandidate: 'Unique Candidate',
    hiddenSingle: 'Hidden Single',
    killerSudokuTips: 'Killer Sudoku Tips',
    speedImprovement: 'Speed Improvement',
    leaderboardDescription: 'Leaderboard by difficulty, showing best scores for each difficulty',
    rankingCriteria: 'Ranking criteria: Score → Best Time → Games Played',
    autoUpdate: 'Leaderboard updates automatically after each game completion',
    transparentScoring: 'Complete scoring process recording ensures fairness and transparency',
    basicScore: 'Basic Score',
    timeBonus: 'Time Bonus',
    mistakePenalty: 'Mistake Penalty',
    calculationFormula: 'Calculation Formula',
    finalScoreFormula: 'Final Score = max(Basic Score × 0.2, Basic Score + Time Bonus - Mistake Penalty)',
    idealTime: 'Ideal Time',
    earlyBonus: 'Early',
    overtimePenalty: 'Overtime',
    mistake: 'Mistake',
    minimumScore: 'Minimum Score',
    example: 'Example',
    points: 'pts',
    minutes: 'min',
    basicRulesDescription: 'Fill numbers 1-9 in a 9×9 grid. Each row, column, and 3×3 box must contain unique numbers.',
    killerSudokuFeaturesDescription: 'Numbers in dashed boxes must sum to the number in the top-left corner, and cannot repeat within the box.',
    solvingStrategyDescription: 'Start with cells that have only one possible number, then gradually deduce other cells.',
    uniqueCandidateDescription: 'If a number has only one possible position in a row, column, or box, that\'s the answer.',
    hiddenSingleDescription: 'If only one number can be placed in a cell, that\'s the answer.',
    killerSudokuTipsDescription: 'Use the sum constraints of dashed boxes to eliminate impossible number combinations.',
    speedImprovementDescription: 'With practice, consider multiple constraints simultaneously to improve solving speed.',
    earlyBonusDescription: '+0.5 points per second early (max 500 points)',
    overtimePenaltyDescription: '-0.1 points per second overtime (min 0 points)',
    idealTimeDescription: 'Easy 6min, Medium 12min, Hard 18min, Expert 24min',
    mistakePenaltyDescription: '20 points deducted per mistake',
    minimumScoreDescription: '20% of basic score',
    minimumScoreExamples: '(Easy 20pts, Medium 40pts, Hard 60pts, Expert 100pts)',
    scoringExample: 'Easy mode, 2 minutes, 1 mistake = 100 + 240 - 20 = 320 points',
    
    // Legal Documents
    legal: {
      privacyPolicy: {
        title: 'Privacy Policy',
        lastUpdated: 'Last updated: January 1, 2025',
        introduction: 'This Privacy Policy describes how Killer Sudoku Score ("we", "our", or "us") collects, uses, and protects your information when you use our web application.',
        informationCollection: 'Information We Collect',
        informationCollectionContent: 'We collect minimal information necessary to provide our service: username (for leaderboard participation), game statistics (scores, completion times), and technical data (browser type, device information).',
        informationUse: 'How We Use Your Information',
        informationUseContent: 'Your information is used solely to: provide game functionality, maintain leaderboards, improve user experience, and ensure service security. We do not sell or share your personal data with third parties.',
        dataStorage: 'Data Storage and Security',
        dataStorageContent: 'Your data is stored securely using industry-standard encryption. We implement appropriate technical and organizational measures to protect against unauthorized access, alteration, disclosure, or destruction.',
        cookies: 'Cookies and Local Storage',
        cookiesContent: 'We use cookies and local storage to remember your preferences, game progress, and language settings. You can disable cookies in your browser settings, though this may affect functionality.',
        userRights: 'Your Rights',
        userRightsContent: 'You have the right to access, update, or delete your personal data. Contact us to exercise these rights. You can also opt out of leaderboard participation by using visitor mode.',
        changes: 'Changes to This Policy',
        changesContent: 'We may update this Privacy Policy periodically. We will notify users of significant changes through our application or website.',
        contact: 'Contact Information',
        contactContent: 'If you have questions about this Privacy Policy, please contact us through our contact page.',
      },
      termsOfService: {
        title: 'Terms of Service',
        lastUpdated: 'Last updated: January 1, 2025',
        acceptance: 'Acceptance of Terms',
        acceptanceContent: 'By accessing and using Killer Sudoku Score, you accept and agree to be bound by the terms and provision of this agreement.',
        serviceDescription: 'Service Description',
        serviceDescriptionContent: 'Killer Sudoku Score is a web-based puzzle game that provides sudoku challenges with scoring systems and leaderboards. The service is provided "as is" without warranties.',
        userConduct: 'User Conduct',
        userConductContent: 'Users agree to: use the service lawfully, not attempt to manipulate scores or rankings, respect other users, and not engage in harmful or disruptive behavior.',
        intellectualProperty: 'Intellectual Property',
        intellectualPropertyContent: 'All content, including game logic, design, and code, is protected by intellectual property laws. Users may not copy, modify, or distribute our content without permission.',
        privacy: 'Privacy',
        privacyContent: 'Your privacy is important to us. Please review our Privacy Policy to understand how we collect and use your information.',
        serviceAvailability: 'Service Availability',
        serviceAvailabilityContent: 'We strive to maintain service availability but cannot guarantee uninterrupted access. We reserve the right to modify or discontinue the service at any time.',
        liability: 'Limitation of Liability',
        liabilityContent: 'To the maximum extent permitted by law, we shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the service.',
        termination: 'Termination',
        terminationContent: 'We may terminate or suspend your access to the service immediately, without prior notice, for any reason, including breach of these terms.',
        governingLaw: 'Governing Law',
        governingLawContent: 'These terms shall be governed by and construed in accordance with applicable laws, without regard to conflict of law principles.',
        changes: 'Changes to Terms',
        changesContent: 'We reserve the right to modify these terms at any time. Continued use of the service after changes constitutes acceptance of new terms.',
        contact: 'Contact Information',
        contactContent: 'For questions about these Terms of Service, please contact us through our contact page.',
      },
      cookiePolicy: {
        title: 'Cookie Policy',
        lastUpdated: 'Last updated: January 1, 2025',
        introduction: 'This Cookie Policy explains how Killer Sudoku Score uses cookies and similar technologies when you visit our website.',
        whatAreCookies: 'What Are Cookies',
        whatAreCookiesContent: 'Cookies are small text files stored on your device when you visit a website. They help websites remember information about your visit.',
        howWeUseCookies: 'How We Use Cookies',
        howWeUseCookiesContent: 'We use cookies to: remember your language preferences, save game progress, maintain user sessions, and improve website functionality.',
        typesOfCookies: 'Types of Cookies We Use',
        essentialCookies: 'Essential Cookies',
        essentialCookiesContent: 'These cookies are necessary for the website to function properly. They enable basic functions like page navigation and access to secure areas.',
        preferenceCookies: 'Preference Cookies',
        preferenceCookiesContent: 'These cookies remember your choices and preferences, such as language settings and theme selection.',
        analyticsCookies: 'Analytics Cookies',
        analyticsCookiesContent: 'These cookies help us understand how visitors interact with our website by collecting anonymous information.',
        managingCookies: 'Managing Cookies',
        managingCookiesContent: 'You can control cookies through your browser settings. However, disabling cookies may affect website functionality.',
        thirdPartyCookies: 'Third-Party Cookies',
        thirdPartyCookiesContent: 'We may use third-party services that set their own cookies. Please review their privacy policies for more information.',
        updates: 'Updates to This Policy',
        updatesContent: 'We may update this Cookie Policy from time to time. Please check this page regularly for any changes.',
        contact: 'Contact Us',
        contactContent: 'If you have questions about our use of cookies, please contact us through our contact page.',
      },
      contact: {
        title: 'Contact Us',
        lastUpdated: 'Last updated: January 1, 2025',
        introduction: 'We welcome your feedback, questions, and suggestions about Killer Sudoku Score.',
        waysToContact: 'Ways to Contact Us',
        email: 'Email',
        emailContent: 'For general inquiries, technical support, or feedback, please send us an email.',
        github: 'GitHub',
        githubContent: 'For technical issues, bug reports, or feature requests, please visit our GitHub repository.',
        responseTime: 'Response Time',
        responseTimeContent: 'We aim to respond to all inquiries within 48 hours during business days.',
        typesOfInquiries: 'Types of Inquiries We Handle',
        technicalSupport: 'Technical Support',
        technicalSupportContent: 'Issues with game functionality, browser compatibility, or performance problems.',
        privacyConcerns: 'Privacy Concerns',
        privacyConcernsContent: 'Questions about data collection, usage, or privacy policy.',
        featureRequests: 'Feature Requests',
        featureRequestsContent: 'Suggestions for new features or improvements to existing functionality.',
        bugReports: 'Bug Reports',
        bugReportsContent: 'Reports of errors, glitches, or unexpected behavior in the game.',
        feedback: 'General Feedback',
        feedbackContent: 'Comments, suggestions, or general feedback about the game experience.',
        beforeContacting: 'Before Contacting Us',
        beforeContactingContent: 'Please check our FAQ section and ensure you are using the latest version of your browser. Many issues can be resolved by clearing browser cache or updating your browser.',
        privacyNote: 'Privacy Note',
        privacyNoteContent: 'When contacting us, please do not include sensitive personal information unless necessary. We will only use your information to respond to your inquiry.',
        businessHours: 'Business Hours',
        businessHoursContent: 'We typically respond to inquiries Monday through Friday, 9 AM to 5 PM (UTC).',
      },
    },
  },
  zh: {
    // 遊戲相關
    gameTitle: '殺手數獨',
    newGame: '新遊戲',
    gameRules: '遊戲規則',
    difficulty: '難度',
    easy: '簡單',
    medium: '中等',
    hard: '困難',
    expert: '專家',
    hell: '地獄',
    
    // 多巴胺模式
    dopamineMode: '多巴胺模式',
    startChallenge: '開始挑戰',
    remaining: '剩餘',
    score: '分數',
    combo: 'COMBO',
    
    // 註解功能
    showNotes: '顯示註解',
    hideNotes: '隱藏註解',
    notes: '註解',
    notesOn: '註解開',
    notesOff: '註解關',
    notesModeOn: '開啟註解模式',
    notesModeOff: '關閉註解模式',
    candidateNumbers: '候選數字',
    
    // 多巴胺資訊卡
    dopamineInfoTitle: '多巴胺模式',
    dopamineInfoSubtitle: '挑戰你的極限！',
    dopamineFeatures: '模式特色',
    dopamineRules: '遊戲規則',
    basicAchievement: '基礎成就感',
    moderateChallenge: '適度挑戰',
    highAchievement: '高成就感',
    topChallenge: '頂級挑戰',
    highestAchievement: '最高成就感',
    selectDifficulty: '選擇難度',
    startDopamineChallenge: '開始挑戰',
    challengeYourLimits: '挑戰極限',
    userLimited: '用戶限定',
    beyondNormalMode: '超越普通模式',
    modeFeatures: '模式特色',
    selectChallengeDifficulty: '選擇挑戰難度',
    chooseDifficultyChallenge: '選擇難度挑戰，專注於特定難度',
    specialScoringSystem: '特殊計分系統，連擊與速度獎勵',
    timeLimitChallenge: '時間限制內完成數獨挑戰',
    errorCountAffectsScore: '錯誤次數影響最終分數',
    consecutiveCorrectReward: '連續正確填寫可獲得連擊獎勵',
    speedCompletionBonus: '完成速度越快，分數加成越高',
    challengeFailed: '挑戰失敗',
    dopamineAchievementWall: '多巴胺成就牆',
    noTopScoreData: '暫無最高分數據',
    difficultyLevel: '難度等級',
    againChallenge: '再次挑戰',
    returnToMainMenu: '返回主選單',
    congratulationsComplete: '恭喜完成',
    successfullyCompletedGame: '您成功完成了遊戲',
    currentRank: '目前排名',
    totalScore: '總分數',
    newRecord: '新紀錄！',
    completionTime: '完成時間',
    errorCount: '錯誤次數',
    playAgain: '再玩一次',
    viewLeaderboardButton: '查看排行榜',
    congratulations: '恭喜',
    remainingTime: '剩餘時間',
    maxCombo: '最大連擊',
    
    // 排行榜
    leaderboard: '排行榜',
    viewLeaderboard: '查看排行榜',
    viewHighestScore: '查看最高分',
    all: '全部',
    gamesPlayed: '場遊戲',
    achievementWall: '成就牆',
    noData: '暫無成就資料',
    highestScoreDisplay: '最高分展示',
    
    // 用戶相關
    welcome: '歡迎',
    welcomeToKillerSudoku: '歡迎來到殺手數獨',
    enterNameToStart: '請輸入您的名稱以開始遊戲並參與排行榜',
    enterYourName: '請輸入您的名稱',
    processing: '處理中...',
    startGame: '開始遊戲',
    visitorMode: '訪客模式',
    visitorModeDescription: '訪客模式不計分，不參與排行榜',
    checkNetworkConnection: '請檢查網路連接或稍後再試。如果問題持續，請聯繫管理員。',
    usernameAlreadyExists: '用戶名稱已註冊，請重新輸入',
    viewStats: '查看統計',
    normal: '普通',
    dopamine: '多巴胺',
    
    // 通用
    close: '關閉',
    back: '返回',
    restart: '再次挑戰',
    returnToMain: '返回主選單',
    clear: '清除',
    
    // 主題
    currentTheme: '當前主題',
    clickToToggle: '點擊切換明暗模式',
    
    // 載入狀態
    loadingStats: '載入統計中...',
    
    // 用戶統計
    bestScore: '最佳分數',
    bestTime: '最佳時間',
    totalGames: '總遊戲數',
    
    // 遊戲規則
    scoringSystem: '計分系統',
    rules: '規則',
    scoring: '計分',
    tips: '解題技巧',
    basicRules: '基本規則',
    killerSudokuFeatures: '殺手特色',
    solvingStrategy: '解題策略',
    uniqueCandidate: '唯一候選數',
    hiddenSingle: '隱藏單數',
    killerSudokuTips: '殺手數獨技巧',
    speedImprovement: '速度提升',
    leaderboardDescription: '排行榜按難度分類，顯示各難度的最佳成績',
    rankingCriteria: '排名依據：分數 → 最佳時間 → 遊戲次數',
    autoUpdate: '每次完成遊戲都會自動更新排行榜',
    transparentScoring: '分數計算過程會完整記錄，確保公平透明',
    basicScore: '基礎分數',
    timeBonus: '時間獎勵',
    mistakePenalty: '錯誤懲罰',
    calculationFormula: '計算公式',
    finalScoreFormula: '最終分數 = max(基礎分數 × 0.2, 基礎分數 + 時間獎勵 - 錯誤懲罰)',
    idealTime: '理想時間',
    earlyBonus: '提前',
    overtimePenalty: '超時',
    mistake: '錯誤',
    minimumScore: '最低分數',
    example: '範例',
    points: '分',
    minutes: '分',
    basicRulesDescription: '在格子中填入數字1-9，每行、每列、每個9宮格都不能重複。',
    killerSudokuFeaturesDescription: '虛線框內的數字必須相加等於左上角數字，框內數字不能重複。',
    solvingStrategyDescription: '先從只有一個可能數字的格子開始，逐步推理其他格子的數字。',
    uniqueCandidateDescription: '在行、列或宮格中，如果某個數字只有一個可能位置，那就是答案。',
    hiddenSingleDescription: '在某個格子中，如果只有一個數字可以填入，那就是答案。',
    killerSudokuTipsDescription: '利用虛線框的總和限制，排除不可能的數字組合。',
    speedImprovementDescription: '熟練後可以同時考慮多個限制條件，提高解題速度。',
    earlyBonusDescription: '每提前1秒+0.5分（最多500分）',
    overtimePenaltyDescription: '每超時1秒-0.1分（最少0分）',
    idealTimeDescription: '簡6分、中12分、難18分、專24分',
    mistakePenaltyDescription: '每個錯誤扣除20分',
    minimumScoreDescription: '基礎分數的20%',
    minimumScoreExamples: '（簡20分、中40分、難60分、專100分）',
    scoringExample: '簡單模式，2分鐘完成，1次錯誤 = 100 + 240 - 20 = 320分',
    
    // 法律文件
    legal: {
      privacyPolicy: {
        title: '隱私政策',
        lastUpdated: '最後更新：2025年1月1日',
        introduction: '本隱私政策說明殺手數獨分數（「我們」、「我們的」或「本公司」）在您使用我們的網路應用程式時如何收集、使用和保護您的資訊。',
        informationCollection: '我們收集的資訊',
        informationCollectionContent: '我們僅收集提供服務所需的最少資訊：用戶名稱（用於排行榜參與）、遊戲統計資料（分數、完成時間）和技術資料（瀏覽器類型、裝置資訊）。',
        informationUse: '我們如何使用您的資訊',
        informationUseContent: '您的資訊僅用於：提供遊戲功能、維護排行榜、改善用戶體驗和確保服務安全。我們不會向第三方出售或分享您的個人資料。',
        dataStorage: '資料儲存與安全',
        dataStorageContent: '您的資料使用業界標準加密技術安全儲存。我們實施適當的技術和組織措施，防止未經授權的存取、更改、揭露或破壞。',
        cookies: 'Cookie與本地儲存',
        cookiesContent: '我們使用Cookie和本地儲存來記住您的偏好設定、遊戲進度和語言設定。您可以在瀏覽器設定中停用Cookie，但這可能會影響功能。',
        userRights: '您的權利',
        userRightsContent: '您有權存取、更新或刪除您的個人資料。請聯繫我們以行使這些權利。您也可以透過使用訪客模式選擇不參與排行榜。',
        changes: '政策變更',
        changesContent: '我們可能會定期更新此隱私政策。我們將透過我們的應用程式或網站通知用戶重大變更。',
        contact: '聯絡資訊',
        contactContent: '如果您對此隱私政策有任何疑問，請透過我們的聯絡頁面與我們聯繫。',
      },
      termsOfService: {
        title: '服務條款',
        lastUpdated: '最後更新：2025年1月1日',
        acceptance: '條款接受',
        acceptanceContent: '透過存取和使用殺手數獨分數，您接受並同意受本協議的條款和規定約束。',
        serviceDescription: '服務說明',
        serviceDescriptionContent: '殺手數獨分數是一個基於網路的益智遊戲，提供數獨挑戰、計分系統和排行榜。服務以「現狀」提供，不提供任何保證。',
        userConduct: '用戶行為',
        userConductContent: '用戶同意：合法使用服務、不嘗試操縱分數或排名、尊重其他用戶，以及不從事有害或破壞性行為。',
        intellectualProperty: '智慧財產權',
        intellectualPropertyContent: '所有內容，包括遊戲邏輯、設計和程式碼，均受智慧財產權法律保護。未經許可，用戶不得複製、修改或分發我們的內容。',
        privacy: '隱私',
        privacyContent: '您的隱私對我們很重要。請查看我們的隱私政策，了解我們如何收集和使用您的資訊。',
        serviceAvailability: '服務可用性',
        serviceAvailabilityContent: '我們努力維持服務可用性，但無法保證不間斷的存取。我們保留隨時修改或停止服務的權利。',
        liability: '責任限制',
        liabilityContent: '在法律允許的最大範圍內，我們不對因您使用服務而產生的任何間接、附帶、特殊、後果性或懲罰性損害負責。',
        termination: '終止',
        terminationContent: '我們可以立即終止或暫停您對服務的存取，無需事先通知，包括違反這些條款的情況。',
        governingLaw: '適用法律',
        governingLawContent: '這些條款應根據適用法律進行解釋和執行，不考慮法律衝突原則。',
        changes: '條款變更',
        changesContent: '我們保留隨時修改這些條款的權利。變更後繼續使用服務即表示接受新條款。',
        contact: '聯絡資訊',
        contactContent: '如果您對這些服務條款有任何疑問，請透過我們的聯絡頁面與我們聯繫。',
      },
      cookiePolicy: {
        title: 'Cookie政策',
        lastUpdated: '最後更新：2025年1月1日',
        introduction: '本Cookie政策說明殺手數獨分數在您造訪我們的網站時如何使用Cookie和類似技術。',
        whatAreCookies: '什麼是Cookie',
        whatAreCookiesContent: 'Cookie是當您造訪網站時儲存在您裝置上的小型文字檔案。它們幫助網站記住您造訪的相關資訊。',
        howWeUseCookies: '我們如何使用Cookie',
        howWeUseCookiesContent: '我們使用Cookie來：記住您的語言偏好、儲存遊戲進度、維持用戶會話，以及改善網站功能。',
        typesOfCookies: '我們使用的Cookie類型',
        essentialCookies: '必要Cookie',
        essentialCookiesContent: '這些Cookie是網站正常運作所必需的。它們啟用基本功能，如頁面導航和存取安全區域。',
        preferenceCookies: '偏好Cookie',
        preferenceCookiesContent: '這些Cookie記住您的選擇和偏好，如語言設定和主題選擇。',
        analyticsCookies: '分析Cookie',
        analyticsCookiesContent: '這些Cookie透過收集匿名資訊幫助我們了解訪客如何與我們的網站互動。',
        managingCookies: '管理Cookie',
        managingCookiesContent: '您可以透過瀏覽器設定控制Cookie。但是，停用Cookie可能會影響網站功能。',
        thirdPartyCookies: '第三方Cookie',
        thirdPartyCookiesContent: '我們可能使用設定自己Cookie的第三方服務。請查看他們的隱私政策以獲取更多資訊。',
        updates: '政策更新',
        updatesContent: '我們可能會不時更新此Cookie政策。請定期檢查此頁面以獲取任何變更。',
        contact: '聯絡我們',
        contactContent: '如果您對我們使用Cookie有任何疑問，請透過我們的聯絡頁面與我們聯繫。',
      },
      contact: {
        title: '聯絡我們',
        lastUpdated: '最後更新：2025年1月1日',
        introduction: '我們歡迎您對殺手數獨分數的意見回饋、問題和建議。',
        waysToContact: '聯絡我們的方式',
        email: '電子郵件',
        emailContent: '對於一般詢問、技術支援或意見回饋，請發送電子郵件給我們。',
        github: 'GitHub',
        githubContent: '對於技術問題、錯誤報告或功能請求，請造訪我們的GitHub儲存庫。',
        responseTime: '回應時間',
        responseTimeContent: '我們目標在營業日內48小時內回應所有詢問。',
        typesOfInquiries: '我們處理的詢問類型',
        technicalSupport: '技術支援',
        technicalSupportContent: '遊戲功能問題、瀏覽器相容性或效能問題。',
        privacyConcerns: '隱私疑慮',
        privacyConcernsContent: '關於資料收集、使用或隱私政策的問題。',
        featureRequests: '功能請求',
        featureRequestsContent: '新功能建議或現有功能的改進建議。',
        bugReports: '錯誤報告',
        bugReportsContent: '遊戲中錯誤、故障或意外行為的報告。',
        feedback: '一般意見回饋',
        feedbackContent: '對遊戲體驗的評論、建議或一般意見回饋。',
        beforeContacting: '聯絡我們之前',
        beforeContactingContent: '請查看我們的常見問題部分，並確保您使用的是最新版本的瀏覽器。許多問題可以透過清除瀏覽器快取或更新瀏覽器來解決。',
        privacyNote: '隱私注意事項',
        privacyNoteContent: '聯絡我們時，除非必要，請勿包含敏感的個人資訊。我們只會使用您的資訊來回應您的詢問。',
        businessHours: '營業時間',
        businessHoursContent: '我們通常在週一至週五上午9點至下午5點（UTC）回應詢問。',
      },
    },
  },
  ko: {
    // 遊戲相關
    gameTitle: '킬러 스도쿠',
    newGame: '새 게임',
    gameRules: '게임 규칙',
    difficulty: '난이도',
    easy: '쉬움',
    medium: '보통',
    hard: '어려움',
    expert: '전문가',
    hell: '지옥',
    
    // 多巴胺 모드
    dopamineMode: '도파민 모드',
    startChallenge: '도전 시작',
    remaining: '남은',
    score: '점수',
    combo: 'COMBO',
    
    // 도파민 정보 카드
    dopamineInfoTitle: '도파민 모드',
    dopamineInfoSubtitle: '한계에 도전하세요!',
    dopamineFeatures: '모드 특징',
    dopamineRules: '게임 규칙',
    basicAchievement: '기본 성취감',
    moderateChallenge: '적당한 도전',
    highAchievement: '높은 성취감',
    topChallenge: '최고 도전',
    highestAchievement: '최고 성취감',
    selectDifficulty: '난이도 선택',
    startDopamineChallenge: '도전 시작',
    challengeYourLimits: '한계에 도전',
    userLimited: '사용자 제한',
    beyondNormalMode: '일반 모드 초월',
    modeFeatures: '모드 특징',
    selectChallengeDifficulty: '도전 난이도 선택',
    chooseDifficultyChallenge: '난이도 도전 선택, 특정 난이도에 집중',
    specialScoringSystem: '특별 점수 시스템, 콤보와 속도 보상',
    timeLimitChallenge: '시간 제한 내에 스도쿠 도전 완료',
    errorCountAffectsScore: '오류 횟수가 최종 점수에 영향',
    consecutiveCorrectReward: '연속 정확한 입력으로 콤보 보상 획득',
    speedCompletionBonus: '완료 속도가 빠를수록 높은 점수 보너스',
    challengeFailed: '도전 실패',
    dopamineAchievementWall: '도파민 성취 벽',
    noTopScoreData: '최고 점수 데이터 없음',
    difficultyLevel: '난이도 레벨',
    againChallenge: '다시 도전',
    returnToMainMenu: '메인 메뉴로 돌아가기',
    congratulationsComplete: '축하합니다 완료',
    successfullyCompletedGame: '게임을 성공적으로 완료했습니다',
    currentRank: '현재 순위',
    totalScore: '총 점수',
    newRecord: '새 기록!',
    completionTime: '완료 시간',
    errorCount: '오류 횟수',
    playAgain: '다시 플레이',
    viewLeaderboardButton: '리더보드 보기',
    congratulations: '축하합니다',
    remainingTime: '남은 시간',
    maxCombo: '최대 콤보',
    
    // 리더보드
    leaderboard: '리더보드',
    viewLeaderboard: '리더보드 보기',
    viewHighestScore: '최고 점수 보기',
    all: '전체',
    gamesPlayed: '게임',
    achievementWall: '성취 벽',
    noData: '데이터 없음',
    highestScoreDisplay: '최고 점수 표시',
    
    // 사용자 관련
    welcome: '환영합니다',
    welcomeToKillerSudoku: '킬러 스도쿠에 오신 것을 환영합니다',
    enterNameToStart: '게임을 시작하고 리더보드에 참여하려면 이름을 입력하세요',
    enterYourName: '이름을 입력하세요',
    processing: '처리 중...',
    startGame: '게임 시작',
    visitorMode: '방문자 모드',
    visitorModeDescription: '방문자 모드는 점수가 기록되지 않으며 리더보드에 참여하지 않습니다',
    checkNetworkConnection: '네트워크 연결을 확인하거나 나중에 다시 시도해주세요. 문제가 지속되면 관리자에게 문의하세요.',
    viewStats: '통계 보기',
    normal: '일반',
    dopamine: '도파민',
    
    // 일반
    close: '닫기',
    back: '뒤로',
    restart: '다시 도전',
    returnToMain: '메인 메뉴로',
    clear: '지우기',
    
    // 테마
    currentTheme: '현재 테마',
    clickToToggle: '라이트/다크 모드 전환',
    
    // 로딩 상태
    loadingStats: '통계 로딩 중...',
    
    // 사용자 통계
    bestScore: '최고 점수',
    bestTime: '최고 시간',
    totalGames: '총 게임 수',
    
    // 게임 규칙
    scoringSystem: '점수 시스템',
    rules: '규칙',
    scoring: '점수',
    tips: '해결 팁',
    basicRules: '기본 규칙',
    killerSudokuFeatures: '킬러 스도쿠 특징',
    solvingStrategy: '해결 전략',
    uniqueCandidate: '유일 후보수',
    hiddenSingle: '숨겨진 단수',
    killerSudokuTips: '킬러 스도쿠 팁',
    speedImprovement: '속도 향상',
    leaderboardDescription: '난이도별 순위표, 각 난이도의 최고 점수 표시',
    rankingCriteria: '순위 기준: 점수 → 최고 시간 → 게임 횟수',
    autoUpdate: '게임 완료 후 순위표 자동 업데이트',
    transparentScoring: '점수 계산 과정 완전 기록으로 공정성과 투명성 보장',
    basicScore: '기본 점수',
    timeBonus: '시간 보너스',
    mistakePenalty: '실수 페널티',
    calculationFormula: '계산 공식',
    finalScoreFormula: '최종 점수 = max(기본 점수 × 0.2, 기본 점수 + 시간 보너스 - 실수 페널티)',
    idealTime: '이상 시간',
    earlyBonus: '조기 완료',
    overtimePenalty: '시간 초과',
    mistake: '실수',
    minimumScore: '최소 점수',
    example: '예시',
    points: '점',
    minutes: '분',
    basicRulesDescription: '9×9 격자에 1-9 숫자를 채우세요. 각 행, 열, 3×3 박스는 고유한 숫자를 포함해야 합니다.',
    killerSudokuFeaturesDescription: '점선 상자 안의 숫자는 왼쪽 상단 숫자의 합과 같아야 하며, 상자 내에서 반복될 수 없습니다.',
    solvingStrategyDescription: '가능한 숫자가 하나뿐인 셀부터 시작하여 다른 셀을 점진적으로 추론하세요.',
    uniqueCandidateDescription: '행, 열 또는 박스에서 숫자가 하나의 가능한 위치만 있다면 그것이 답입니다.',
    hiddenSingleDescription: '셀에 하나의 숫자만 넣을 수 있다면 그것이 답입니다.',
    killerSudokuTipsDescription: '점선 상자의 합 제약을 활용하여 불가능한 숫자 조합을 제거하세요.',
    speedImprovementDescription: '연습을 통해 여러 제약을 동시에 고려하여 해결 속도를 향상시키세요.',
    earlyBonusDescription: '1초당 +0.5점 조기 완료 (최대 500점)',
    overtimePenaltyDescription: '1초당 -0.1점 시간 초과 (최소 0점)',
    idealTimeDescription: '쉬움 6분, 보통 12분, 어려움 18분, 전문가 24분',
    mistakePenaltyDescription: '실수당 20점 차감',
    minimumScoreDescription: '기본 점수의 20%',
    minimumScoreExamples: '(쉬움 20점, 보통 40점, 어려움 60점, 전문가 100점)',
    scoringExample: '쉬움 모드, 2분 완료, 1회 실수 = 100 + 240 - 20 = 320점',
    
    // 법적 문서
    legal: {
      privacyPolicy: {
        title: '개인정보처리방침',
        lastUpdated: '최종 업데이트: 2025년 1월 1일',
        introduction: '본 개인정보처리방침은 킬러 스도쿠 스코어("우리", "저희", "회사")가 웹 애플리케이션을 사용할 때 귀하의 정보를 수집, 사용 및 보호하는 방법을 설명합니다.',
        informationCollection: '수집하는 정보',
        informationCollectionContent: '저희는 서비스 제공에 필요한 최소한의 정보만 수집합니다: 사용자명(리더보드 참여용), 게임 통계(점수, 완료 시간), 기술 데이터(브라우저 유형, 기기 정보).',
        informationUse: '정보 사용 방법',
        informationUseContent: '귀하의 정보는 다음 목적으로만 사용됩니다: 게임 기능 제공, 리더보드 유지, 사용자 경험 개선, 서비스 보안 확보. 저희는 귀하의 개인 데이터를 제3자에게 판매하거나 공유하지 않습니다.',
        dataStorage: '데이터 저장 및 보안',
        dataStorageContent: '귀하의 데이터는 업계 표준 암호화를 사용하여 안전하게 저장됩니다. 저희는 무단 접근, 변경, 공개 또는 파괴로부터 보호하기 위한 적절한 기술적 및 조직적 조치를 구현합니다.',
        cookies: '쿠키 및 로컬 저장소',
        cookiesContent: '저희는 쿠키와 로컬 저장소를 사용하여 귀하의 환경설정, 게임 진행 상황 및 언어 설정을 기억합니다. 브라우저 설정에서 쿠키를 비활성화할 수 있지만, 이는 기능에 영향을 줄 수 있습니다.',
        userRights: '귀하의 권리',
        userRightsContent: '귀하는 개인 데이터에 접근, 업데이트 또는 삭제할 권리가 있습니다. 이러한 권리를 행사하려면 저희에게 연락하세요. 방문자 모드를 사용하여 리더보드 참여를 거부할 수도 있습니다.',
        changes: '정책 변경',
        changesContent: '저희는 이 개인정보처리방침을 주기적으로 업데이트할 수 있습니다. 중요한 변경사항이 있을 경우 애플리케이션이나 웹사이트를 통해 사용자에게 알려드립니다.',
        contact: '연락처 정보',
        contactContent: '이 개인정보처리방침에 대한 질문이 있으시면 연락처 페이지를 통해 저희에게 연락하세요.',
      },
      termsOfService: {
        title: '서비스 이용약관',
        lastUpdated: '최종 업데이트: 2025년 1월 1일',
        acceptance: '약관 수락',
        acceptanceContent: '킬러 스도쿠 스코어에 접근하고 사용함으로써 귀하는 이 계약의 약관 및 조항에 구속되는 것에 동의합니다.',
        serviceDescription: '서비스 설명',
        serviceDescriptionContent: '킬러 스도쿠 스코어는 점수 시스템과 리더보드가 있는 스도쿠 도전을 제공하는 웹 기반 퍼즐 게임입니다. 서비스는 보증 없이 "있는 그대로" 제공됩니다.',
        userConduct: '사용자 행동',
        userConductContent: '사용자는 다음에 동의합니다: 서비스를 합법적으로 사용하고, 점수나 순위를 조작하려고 시도하지 않으며, 다른 사용자를 존중하고, 해로운 또는 방해가 되는 행동에 관여하지 않습니다.',
        intellectualProperty: '지적재산권',
        intellectualPropertyContent: '게임 로직, 디자인 및 코드를 포함한 모든 콘텐츠는 지적재산권 법률에 의해 보호됩니다. 사용자는 허가 없이 저희 콘텐츠를 복사, 수정 또는 배포할 수 없습니다.',
        privacy: '개인정보보호',
        privacyContent: '귀하의 개인정보보호는 저희에게 중요합니다. 저희가 귀하의 정보를 수집하고 사용하는 방법을 이해하려면 개인정보처리방침을 검토해 주세요.',
        serviceAvailability: '서비스 가용성',
        serviceAvailabilityContent: '저희는 서비스 가용성을 유지하기 위해 노력하지만 중단 없는 접근을 보장할 수는 없습니다. 저희는 언제든지 서비스를 수정하거나 중단할 권리를 보유합니다.',
        liability: '책임 제한',
        liabilityContent: '법률이 허용하는 최대 범위 내에서 저희는 서비스 사용으로 인해 발생하는 간접적, 부수적, 특별, 결과적 또는 징벌적 손해에 대해 책임지지 않습니다.',
        termination: '계약 해지',
        terminationContent: '저희는 이러한 약관 위반을 포함하여 어떤 이유로든 사전 통지 없이 귀하의 서비스 접근을 즉시 종료하거나 중단할 수 있습니다.',
        governingLaw: '준거법',
        governingLawContent: '이 약관은 법률 충돌 원칙을 고려하지 않고 적용 가능한 법률에 따라 해석되고 적용됩니다.',
        changes: '약관 변경',
        changesContent: '저희는 언제든지 이 약관을 수정할 권리를 보유합니다. 변경 후 서비스를 계속 사용하는 것은 새로운 약관에 대한 수락을 의미합니다.',
        contact: '연락처 정보',
        contactContent: '이 서비스 이용약관에 대한 질문이 있으시면 연락처 페이지를 통해 저희에게 연락하세요.',
      },
      cookiePolicy: {
        title: '쿠키 정책',
        lastUpdated: '최종 업데이트: 2025년 1월 1일',
        introduction: '본 쿠키 정책은 킬러 스도쿠 스코어가 귀하가 저희 웹사이트를 방문할 때 쿠키와 유사한 기술을 사용하는 방법을 설명합니다.',
        whatAreCookies: '쿠키란 무엇인가',
        whatAreCookiesContent: '쿠키는 웹사이트를 방문할 때 기기에 저장되는 작은 텍스트 파일입니다. 웹사이트가 방문에 대한 정보를 기억하는 데 도움이 됩니다.',
        howWeUseCookies: '쿠키 사용 방법',
        howWeUseCookiesContent: '저희는 쿠키를 사용하여: 언어 환경설정을 기억하고, 게임 진행 상황을 저장하며, 사용자 세션을 유지하고, 웹사이트 기능을 개선합니다.',
        typesOfCookies: '사용하는 쿠키 유형',
        essentialCookies: '필수 쿠키',
        essentialCookiesContent: '이러한 쿠키는 웹사이트가 제대로 작동하는 데 필요합니다. 페이지 탐색 및 보안 영역 접근과 같은 기본 기능을 활성화합니다.',
        preferenceCookies: '환경설정 쿠키',
        preferenceCookiesContent: '이러한 쿠키는 언어 설정 및 테마 선택과 같은 귀하의 선택과 환경설정을 기억합니다.',
        analyticsCookies: '분석 쿠키',
        analyticsCookiesContent: '이러한 쿠키는 익명 정보를 수집하여 방문자가 저희 웹사이트와 어떻게 상호작용하는지 이해하는 데 도움이 됩니다.',
        managingCookies: '쿠키 관리',
        managingCookiesContent: '브라우저 설정을 통해 쿠키를 제어할 수 있습니다. 그러나 쿠키를 비활성화하면 웹사이트 기능에 영향을 줄 수 있습니다.',
        thirdPartyCookies: '제3자 쿠키',
        thirdPartyCookiesContent: '저희는 자체 쿠키를 설정하는 제3자 서비스를 사용할 수 있습니다. 더 많은 정보는 해당 서비스의 개인정보처리방침을 검토해 주세요.',
        updates: '정책 업데이트',
        updatesContent: '저희는 이 쿠키 정책을 수시로 업데이트할 수 있습니다. 변경사항을 확인하려면 이 페이지를 정기적으로 확인해 주세요.',
        contact: '문의하기',
        contactContent: '쿠키 사용에 대한 질문이 있으시면 연락처 페이지를 통해 저희에게 연락하세요.',
      },
      contact: {
        title: '문의하기',
        lastUpdated: '최종 업데이트: 2025년 1월 1일',
        introduction: '저희는 킬러 스도쿠 스코어에 대한 귀하의 피드백, 질문 및 제안을 환영합니다.',
        waysToContact: '연락 방법',
        email: '이메일',
        emailContent: '일반 문의, 기술 지원 또는 피드백의 경우 이메일을 보내주세요.',
        github: 'GitHub',
        githubContent: '기술적 문제, 버그 리포트 또는 기능 요청의 경우 저희 GitHub 저장소를 방문해 주세요.',
        responseTime: '응답 시간',
        responseTimeContent: '저희는 영업일 기준 48시간 내에 모든 문의에 응답하는 것을 목표로 합니다.',
        typesOfInquiries: '처리하는 문의 유형',
        technicalSupport: '기술 지원',
        technicalSupportContent: '게임 기능 문제, 브라우저 호환성 또는 성능 문제.',
        privacyConcerns: '개인정보보호 우려',
        privacyConcernsContent: '데이터 수집, 사용 또는 개인정보처리방침에 대한 질문.',
        featureRequests: '기능 요청',
        featureRequestsContent: '새로운 기능이나 기존 기능 개선에 대한 제안.',
        bugReports: '버그 리포트',
        bugReportsContent: '게임의 오류, 결함 또는 예상치 못한 동작에 대한 보고.',
        feedback: '일반 피드백',
        feedbackContent: '게임 경험에 대한 의견, 제안 또는 일반적인 피드백.',
        beforeContacting: '문의하기 전에',
        beforeContactingContent: 'FAQ 섹션을 확인하고 최신 버전의 브라우저를 사용하고 있는지 확인해 주세요. 많은 문제는 브라우저 캐시를 지우거나 브라우저를 업데이트하여 해결할 수 있습니다.',
        privacyNote: '개인정보보호 참고사항',
        privacyNoteContent: '문의할 때는 필요하지 않은 한 민감한 개인 정보를 포함하지 마세요. 저희는 귀하의 정보를 문의에 응답하는 목적으로만 사용합니다.',
        businessHours: '영업 시간',
        businessHoursContent: '저희는 일반적으로 월요일부터 금요일까지 오전 9시부터 오후 5시(UTC)까지 문의에 응답합니다.',
      },
    },
  },
  ja: {
    // ゲーム関連
    gameTitle: 'キラー数独',
    newGame: '新しいゲーム',
    gameRules: 'ゲームルール',
    difficulty: '難易度',
    easy: '初級',
    medium: '中級',
    hard: '上級',
    expert: '達人級',
    hell: '地獄級',
    
    // ドーパミンモード
    dopamineMode: 'ドーパミンモード',
    startChallenge: 'チャレンジ開始',
    remaining: '残り',
    score: 'スコア',
    combo: 'COMBO',
    
    // ドーパミン情報カード
    dopamineInfoTitle: 'ドーパミンモード',
    dopamineInfoSubtitle: '限界に挑戦しよう！',
    dopamineFeatures: 'モード特徴',
    dopamineRules: 'ゲームルール',
    basicAchievement: '基本達成感',
    moderateChallenge: '適度な挑戦',
    highAchievement: '高い達成感',
    topChallenge: '最高挑戦',
    highestAchievement: '最高達成感',
    selectDifficulty: '難易度選択',
    startDopamineChallenge: 'チャレンジ開始',
    challengeYourLimits: '限界に挑戦',
    userLimited: 'ユーザー限定',
    beyondNormalMode: '通常モードを超越',
    modeFeatures: 'モード特徴',
    selectChallengeDifficulty: 'チャレンジ難易度選択',
    chooseDifficultyChallenge: '難易度チャレンジ選択、特定の難易度に集中',
    specialScoringSystem: '特別スコアシステム、コンボとスピード報酬',
    timeLimitChallenge: '時間制限内に数独チャレンジ完了',
    errorCountAffectsScore: 'エラー回数が最終スコアに影響',
    consecutiveCorrectReward: '連続正解入力でコンボ報酬獲得',
    speedCompletionBonus: '完了速度が速いほど高いスコアボーナス',
    challengeFailed: 'チャレンジ失敗',
    dopamineAchievementWall: 'ドーパミン実績ウォール',
    noTopScoreData: '最高スコアデータなし',
    difficultyLevel: '難易度レベル',
    againChallenge: '再チャレンジ',
    returnToMainMenu: 'メインメニューに戻る',
    congratulationsComplete: 'おめでとうございます 完了',
    successfullyCompletedGame: 'ゲームを正常に完了しました',
    currentRank: '現在のランク',
    totalScore: '総スコア',
    newRecord: '新記録！',
    completionTime: '完了時間',
    errorCount: 'エラー回数',
    playAgain: 'もう一度プレイ',
    viewLeaderboardButton: 'リーダーボードを見る',
    congratulations: 'おめでとうございます',
    remainingTime: '残り時間',
    maxCombo: '最大コンボ',
    
    // リーダーボード
    leaderboard: 'リーダーボード',
    viewLeaderboard: 'リーダーボードを見る',
    viewHighestScore: '最高スコアを見る',
    all: '全て',
    gamesPlayed: 'ゲーム',
    achievementWall: '実績ウォール',
    noData: 'データなし',
    highestScoreDisplay: '最高スコア表示',
    
    // ユーザー関連
    welcome: 'ようこそ',
    welcomeToKillerSudoku: 'キラー数独へようこそ',
    enterNameToStart: 'ゲームを開始し、リーダーボードに参加するために名前を入力してください',
    enterYourName: '名前を入力してください',
    processing: '処理中...',
    startGame: 'ゲーム開始',
    visitorMode: 'ゲストモード',
    visitorModeDescription: 'ゲストモードはスコアが記録されず、リーダーボードに参加しません',
    checkNetworkConnection: 'ネットワーク接続を確認するか、後でもう一度お試しください。問題が続く場合は、管理者にお問い合わせください。',
    viewStats: '統計を見る',
    normal: '通常',
    dopamine: 'ドーパミン',
    
    // 一般
    close: '閉じる',
    back: '戻る',
    restart: '再挑戦',
    returnToMain: 'メインメニューに戻る',
    clear: 'クリア',
    
    // テーマ
    currentTheme: '現在のテーマ',
    clickToToggle: 'ライト/ダークモード切り替え',
    
    // ローディング状態
    loadingStats: '統計読み込み中...',
    
    // ユーザー統計
    bestScore: '最高スコア',
    bestTime: '最高時間',
    totalGames: '総ゲーム数',
    
    // ゲームルール
    scoringSystem: 'スコアシステム',
    rules: 'ルール',
    scoring: 'スコア',
    tips: '解法のコツ',
    basicRules: '基本ルール',
    killerSudokuFeatures: 'キラー数独の特徴',
    solvingStrategy: '解法戦略',
    uniqueCandidate: '唯一候補数',
    hiddenSingle: '隠れた単数',
    killerSudokuTips: 'キラー数独のコツ',
    speedImprovement: '速度向上',
    leaderboardDescription: '難易度別ランキング、各難易度の最高スコア表示',
    rankingCriteria: 'ランキング基準：スコア → 最高時間 → ゲーム回数',
    autoUpdate: 'ゲーム完了後ランキング自動更新',
    transparentScoring: 'スコア計算過程完全記録で公平性と透明性を保証',
    basicScore: '基本スコア',
    timeBonus: '時間ボーナス',
    mistakePenalty: 'ミスペナルティ',
    calculationFormula: '計算式',
    finalScoreFormula: '最終スコア = max(基本スコア × 0.2, 基本スコア + 時間ボーナス - ミスペナルティ)',
    idealTime: '理想時間',
    earlyBonus: '早期完了',
    overtimePenalty: '時間超過',
    mistake: 'ミス',
    minimumScore: '最低スコア',
    example: '例',
    points: '点',
    minutes: '分',
    basicRulesDescription: '9×9のグリッドに1-9の数字を埋めてください。各行、列、3×3ボックスは一意の数字を含む必要があります。',
    killerSudokuFeaturesDescription: '破線ボックス内の数字は左上の数字の合計と等しく、ボックス内で重複してはいけません。',
    solvingStrategyDescription: '可能な数字が1つしかないセルから始めて、他のセルを段階的に推論してください。',
    uniqueCandidateDescription: '行、列、またはボックスで数字が1つの可能な位置しかない場合、それが答えです。',
    hiddenSingleDescription: 'セルに1つの数字しか入れられない場合、それが答えです。',
    killerSudokuTipsDescription: '破線ボックスの合計制約を活用して、不可能な数字の組み合わせを排除してください。',
    speedImprovementDescription: '練習により複数の制約を同時に考慮して、解決速度を向上させてください。',
    earlyBonusDescription: '1秒あたり+0.5点早期完了（最大500点）',
    overtimePenaltyDescription: '1秒あたり-0.1点時間超過（最小0点）',
    idealTimeDescription: '簡単6分、普通12分、困難18分、専門家24分',
    mistakePenaltyDescription: 'ミス1回につき20点減点',
    minimumScoreDescription: '基本スコアの20%',
    minimumScoreExamples: '（簡単20点、普通40点、困難60点、専門家100点）',
    scoringExample: '簡単モード、2分完了、1回ミス = 100 + 240 - 20 = 320点',
    
    // 法的文書
    legal: {
      privacyPolicy: {
        title: 'プライバシーポリシー',
        lastUpdated: '最終更新：2025年1月1日',
        introduction: 'このプライバシーポリシーは、キラー数独スコア（「当社」、「私たち」）がウェブアプリケーションをご利用いただく際に、お客様の情報をどのように収集、使用、保護するかを説明します。',
        informationCollection: '収集する情報',
        informationCollectionContent: '当社は、サービス提供に必要な最小限の情報のみを収集します：ユーザー名（リーダーボード参加用）、ゲーム統計（スコア、完了時間）、技術データ（ブラウザタイプ、デバイス情報）。',
        informationUse: '情報の使用方法',
        informationUseContent: 'お客様の情報は以下の目的でのみ使用されます：ゲーム機能の提供、リーダーボードの維持、ユーザー体験の向上、サービスセキュリティの確保。当社はお客様の個人データを第三者に販売または共有することはありません。',
        dataStorage: 'データ保存とセキュリティ',
        dataStorageContent: 'お客様のデータは業界標準の暗号化を使用して安全に保存されます。当社は、不正アクセス、変更、開示、または破壊から保護するための適切な技術的および組織的措置を実装しています。',
        cookies: 'Cookieとローカルストレージ',
        cookiesContent: '当社はCookieとローカルストレージを使用して、お客様の設定、ゲーム進行状況、言語設定を記憶します。ブラウザ設定でCookieを無効にすることができますが、これにより機能に影響する場合があります。',
        userRights: 'お客様の権利',
        userRightsContent: 'お客様には個人データへのアクセス、更新、削除する権利があります。これらの権利を行使するには、当社にお問い合わせください。ゲストモードを使用してリーダーボード参加を拒否することもできます。',
        changes: 'ポリシーの変更',
        changesContent: '当社はこのプライバシーポリシーを定期的に更新する場合があります。重要な変更については、アプリケーションまたはウェブサイトを通じてユーザーに通知します。',
        contact: 'お問い合わせ情報',
        contactContent: 'このプライバシーポリシーについてご質問がございましたら、お問い合わせページから当社までご連絡ください。',
      },
      termsOfService: {
        title: '利用規約',
        lastUpdated: '最終更新：2025年1月1日',
        acceptance: '規約の承諾',
        acceptanceContent: 'キラー数独スコアにアクセスし使用することにより、お客様はこの契約の条項および規定に拘束されることに同意します。',
        serviceDescription: 'サービス説明',
        serviceDescriptionContent: 'キラー数独スコアは、スコアシステムとリーダーボードを備えた数独チャレンジを提供するウェブベースのパズルゲームです。サービスは保証なしで「現状のまま」提供されます。',
        userConduct: 'ユーザーの行動',
        userConductContent: 'ユーザーは以下に同意します：サービスを合法的に使用し、スコアやランキングを操作しようとせず、他のユーザーを尊重し、有害または破壊的な行動に従事しないこと。',
        intellectualProperty: '知的財産権',
        intellectualPropertyContent: 'ゲームロジック、デザイン、コードを含むすべてのコンテンツは、知的財産権法によって保護されています。ユーザーは許可なく当社のコンテンツを複製、変更、または配布することはできません。',
        privacy: 'プライバシー',
        privacyContent: 'お客様のプライバシーは当社にとって重要です。当社がお客様の情報をどのように収集し使用するかを理解するために、プライバシーポリシーをご確認ください。',
        serviceAvailability: 'サービスの可用性',
        serviceAvailabilityContent: '当社はサービスの可用性を維持するよう努めますが、中断のないアクセスを保証することはできません。当社はいつでもサービスを変更または中止する権利を留保します。',
        liability: '責任の制限',
        liabilityContent: '法律で許可される最大限の範囲で、当社はサービスの使用に起因する間接的、付随的、特別、結果的、または懲罰的損害について責任を負いません。',
        termination: '契約終了',
        terminationContent: '当社は、これらの規約の違反を含む、いかなる理由でも事前通知なしに、お客様のサービスアクセスを即座に終了または停止することができます。',
        governingLaw: '準拠法',
        governingLawContent: 'これらの規約は、法の抵触原則を考慮せずに、適用される法律に従って解釈され適用されます。',
        changes: '規約の変更',
        changesContent: '当社はいつでもこれらの規約を変更する権利を留保します。変更後のサービスの継続使用は、新しい規約の受諾を意味します。',
        contact: 'お問い合わせ情報',
        contactContent: 'この利用規約についてご質問がございましたら、お問い合わせページから当社までご連絡ください。',
      },
      cookiePolicy: {
        title: 'Cookieポリシー',
        lastUpdated: '最終更新：2025年1月1日',
        introduction: 'このCookieポリシーは、キラー数独スコアがお客様が当社のウェブサイトを訪問する際にCookieと類似の技術をどのように使用するかを説明します。',
        whatAreCookies: 'Cookieとは',
        whatAreCookiesContent: 'Cookieは、ウェブサイトを訪問する際にデバイスに保存される小さなテキストファイルです。ウェブサイトが訪問に関する情報を記憶するのに役立ちます。',
        howWeUseCookies: 'Cookieの使用方法',
        howWeUseCookiesContent: '当社はCookieを使用して：言語設定を記憶し、ゲーム進行状況を保存し、ユーザーセッションを維持し、ウェブサイト機能を向上させます。',
        typesOfCookies: '使用するCookieの種類',
        essentialCookies: '必須Cookie',
        essentialCookiesContent: 'これらのCookieは、ウェブサイトが適切に機能するために必要です。ページナビゲーションやセキュアエリアへのアクセスなどの基本機能を有効にします。',
        preferenceCookies: '設定Cookie',
        preferenceCookiesContent: 'これらのCookieは、言語設定やテーマ選択など、お客様の選択と設定を記憶します。',
        analyticsCookies: '分析Cookie',
        analyticsCookiesContent: 'これらのCookieは、匿名情報を収集することで、訪問者が当社のウェブサイトとどのように相互作用するかを理解するのに役立ちます。',
        managingCookies: 'Cookieの管理',
        managingCookiesContent: 'ブラウザ設定を通じてCookieを制御できます。ただし、Cookieを無効にすると、ウェブサイトの機能に影響する場合があります。',
        thirdPartyCookies: '第三者Cookie',
        thirdPartyCookiesContent: '当社は独自のCookieを設定する第三者サービスを使用する場合があります。詳細については、それらのプライバシーポリシーをご確認ください。',
        updates: 'ポリシーの更新',
        updatesContent: '当社はこのCookieポリシーを随時更新する場合があります。変更を確認するには、このページを定期的にご確認ください。',
        contact: 'お問い合わせ',
        contactContent: 'Cookieの使用についてご質問がございましたら、お問い合わせページから当社までご連絡ください。',
      },
      contact: {
        title: 'お問い合わせ',
        lastUpdated: '最終更新：2025年1月1日',
        introduction: '当社は、キラー数独スコアに関するお客様のフィードバック、ご質問、ご提案を歓迎いたします。',
        waysToContact: 'お問い合わせ方法',
        email: 'メール',
        emailContent: '一般的なお問い合わせ、技術サポート、またはフィードバックについては、メールをお送りください。',
        github: 'GitHub',
        githubContent: '技術的な問題、バグレポート、または機能リクエストについては、当社のGitHubリポジトリをご訪問ください。',
        responseTime: '応答時間',
        responseTimeContent: '当社は営業日48時間以内にすべてのお問い合わせに応答することを目標としています。',
        typesOfInquiries: '対応するお問い合わせの種類',
        technicalSupport: '技術サポート',
        technicalSupportContent: 'ゲーム機能の問題、ブラウザ互換性、またはパフォーマンスの問題。',
        privacyConcerns: 'プライバシーの懸念',
        privacyConcernsContent: 'データ収集、使用、またはプライバシーポリシーに関するご質問。',
        featureRequests: '機能リクエスト',
        featureRequestsContent: '新機能や既存機能の改善に関するご提案。',
        bugReports: 'バグレポート',
        bugReportsContent: 'ゲームのエラー、不具合、または予期しない動作の報告。',
        feedback: '一般的なフィードバック',
        feedbackContent: 'ゲーム体験に関するコメント、ご提案、または一般的なフィードバック。',
        beforeContacting: 'お問い合わせ前に',
        beforeContactingContent: 'FAQセクションをご確認いただき、最新バージョンのブラウザをご使用いただいていることを確認してください。多くの問題は、ブラウザキャッシュをクリアするか、ブラウザを更新することで解決できます。',
        privacyNote: 'プライバシーに関する注意事項',
        privacyNoteContent: 'お問い合わせの際は、必要でない限り機密性の高い個人情報を含めないでください。当社はお客様の情報をお問い合わせへの応答目的でのみ使用します。',
        businessHours: '営業時間',
        businessHoursContent: '当社は通常、月曜日から金曜日の午前9時から午後5時（UTC）にお問い合わせに応答します。',
      },
    },
  },
};

export const useLanguage = () => {
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    // 監聽語言變更事件
    const handleLanguageChange = (event: CustomEvent) => {
      setLanguage(event.detail.language);
    };

    window.addEventListener('languageChange', handleLanguageChange as EventListener);
    
    // 初始化語言
    const savedLanguage = localStorage.getItem('killer-sudoku-language') as Language;
    if (savedLanguage && ['en', 'zh', 'ko', 'ja'].includes(savedLanguage)) {
      setLanguage(savedLanguage);
    }

    return () => {
      window.removeEventListener('languageChange', handleLanguageChange as EventListener);
    };
  }, []);

  const t = (key: keyof typeof translations.en | string) => {
    return translations[language][key as keyof typeof translations.en] || translations.en[key as keyof typeof translations.en] || key;
  };

  return { language, t };
};
