import { useState, useEffect } from 'react';
import { Language } from '@/components/LanguageToggle';

// 語言翻譯對象
const translations = {
  en: {
    // 遊戲相關
    gameTitle: 'Sudoku',
    newGame: 'New Game',
    gameRules: 'Game Rules',
    difficulty: 'Difficulty',
    easy: 'Easy',
    medium: 'Medium',
    hard: 'Hard',
    expert: 'Expert',
    hell: 'Hell',
    
    // 多巴胺模式
    dopamineMode: 'Dopamine Mode',
    startChallenge: 'Start Challenge',
    remaining: 'Remaining',
    score: 'Score',
    combo: 'COMBO',
    
    // 多巴胺資訊卡
    dopamineInfoTitle: 'Dopamine Mode',
    dopamineInfoSubtitle: 'Challenge Your Limits!',
    dopamineFeatures: 'Mode Features',
    dopamineRules: 'Game Rules',
    basicAchievement: 'Basic Achievement',
    moderateChallenge: 'Moderate Challenge',
    highAchievement: 'High Achievement',
    topChallenge: 'Top Challenge',
    highestAchievement: 'Highest Achievement',
    selectDifficulty: 'Select Difficulty',
    startDopamineChallenge: 'Start Challenge',
    challengeYourLimits: 'Challenge Your Limits',
    userLimited: 'User Limited',
    beyondNormalMode: 'Beyond Normal Mode',
    modeFeatures: 'Mode Features',
    selectChallengeDifficulty: 'Select Challenge Difficulty',
    chooseDifficultyChallenge: 'Choose difficulty challenge, focus on specific difficulty',
    specialScoringSystem: 'Special scoring system, combo and speed rewards',
    timeLimitChallenge: 'Complete sudoku challenge within time limit',
    errorCountAffectsScore: 'Error count affects final score',
    consecutiveCorrectReward: 'Consecutive correct filling can get combo reward',
    speedCompletionBonus: 'Faster completion gives higher score bonus',
    challengeFailed: 'Challenge Failed',
    dopamineAchievementWall: 'Dopamine Achievement Wall',
    noTopScoreData: 'No Top Score Data',
    difficultyLevel: 'Difficulty Level',
    againChallenge: 'Challenge Again',
    returnToMainMenu: 'Return to Main Menu',
    congratulationsComplete: 'Congratulations Complete',
    successfullyCompletedGame: 'You have successfully completed the game',
    currentRank: 'Current Rank',
    totalScore: 'Total Score',
    newRecord: 'New Record!',
    completionTime: 'Completion Time',
    errorCount: 'Error Count',
    playAgain: 'Play Again',
    viewLeaderboardButton: 'View Leaderboard',
    congratulations: 'Congratulations',
    remainingTime: 'Remaining Time',
    maxCombo: 'Max Combo',
    
    // 排行榜
    leaderboard: 'Leaderboard',
    viewLeaderboard: 'View Leaderboard',
    viewHighestScore: 'View Highest Score',
    all: 'All',
    gamesPlayed: 'Games Played',
    achievementWall: 'Achievement Wall',
    noData: 'No Data',
    highestScoreDisplay: 'Highest Score Display',
    
    // 用戶相關
    welcome: 'Welcome',
    viewStats: 'View Stats',
    normal: 'Normal',
    dopamine: 'Dopamine',
    
    // 通用
    close: 'Close',
    back: 'Back',
    restart: 'Restart',
    returnToMain: 'Return to Main Menu',
    
    // 主題
    currentTheme: 'Current theme',
    clickToToggle: 'Click to toggle between light and dark',
    
    // 載入狀態
    loadingStats: 'Loading stats...',
    
    // 用戶統計
    bestScore: 'Best Score',
    bestTime: 'Best Time',
    totalGames: 'Total Games',
    
    // 遊戲規則
    scoringSystem: 'Scoring System',
    rules: 'Rules',
    scoring: 'Scoring',
    tips: 'Tips',
    basicRules: 'Basic Rules',
    killerSudokuFeatures: 'Killer Sudoku Features',
    solvingStrategy: 'Solving Strategy',
    uniqueCandidate: 'Unique Candidate',
    hiddenSingle: 'Hidden Single',
    killerSudokuTips: 'Killer Sudoku Tips',
    speedImprovement: 'Speed Improvement',
    leaderboardDescription: 'Leaderboard by difficulty, showing best scores for each difficulty',
    rankingCriteria: 'Ranking criteria: Score → Best Time → Games Played',
    autoUpdate: 'Leaderboard updates automatically after each game completion',
    transparentScoring: 'Complete scoring process recording ensures fairness and transparency',
    basicScore: 'Basic Score',
    timeBonus: 'Time Bonus',
    mistakePenalty: 'Mistake Penalty',
    calculationFormula: 'Calculation Formula',
    finalScoreFormula: 'Final Score = max(Basic Score × 0.2, Basic Score + Time Bonus - Mistake Penalty)',
    idealTime: 'Ideal Time',
    earlyBonus: 'Early',
    overtimePenalty: 'Overtime',
    mistake: 'Mistake',
    minimumScore: 'Minimum Score',
    example: 'Example',
    points: 'pts',
    minutes: 'min',
    basicRulesDescription: 'Fill numbers 1-9 in a 9×9 grid. Each row, column, and 3×3 box must contain unique numbers.',
    killerSudokuFeaturesDescription: 'Numbers in dashed boxes must sum to the number in the top-left corner, and cannot repeat within the box.',
    solvingStrategyDescription: 'Start with cells that have only one possible number, then gradually deduce other cells.',
    uniqueCandidateDescription: 'If a number has only one possible position in a row, column, or box, that\'s the answer.',
    hiddenSingleDescription: 'If only one number can be placed in a cell, that\'s the answer.',
    killerSudokuTipsDescription: 'Use the sum constraints of dashed boxes to eliminate impossible number combinations.',
    speedImprovementDescription: 'With practice, consider multiple constraints simultaneously to improve solving speed.',
    earlyBonusDescription: '+0.5 points per second early (max 500 points)',
    overtimePenaltyDescription: '-0.1 points per second overtime (min 0 points)',
    idealTimeDescription: 'Easy 6min, Medium 12min, Hard 18min, Expert 24min',
    mistakePenaltyDescription: '20 points deducted per mistake',
    minimumScoreDescription: '20% of basic score',
    minimumScoreExamples: '(Easy 20pts, Medium 40pts, Hard 60pts, Expert 100pts)',
    scoringExample: 'Easy mode, 2 minutes, 1 mistake = 100 + 240 - 20 = 320 points',
  },
  zh: {
    // 遊戲相關
    gameTitle: '殺手數獨',
    newGame: '新遊戲',
    gameRules: '遊戲規則',
    difficulty: '難度',
    easy: '簡單',
    medium: '中等',
    hard: '困難',
    expert: '專家',
    hell: '地獄',
    
    // 多巴胺模式
    dopamineMode: '多巴胺模式',
    startChallenge: '開始挑戰',
    remaining: '剩餘',
    score: '分數',
    combo: 'COMBO',
    
    // 多巴胺資訊卡
    dopamineInfoTitle: '多巴胺模式',
    dopamineInfoSubtitle: '挑戰你的極限！',
    dopamineFeatures: '模式特色',
    dopamineRules: '遊戲規則',
    basicAchievement: '基礎成就感',
    moderateChallenge: '適度挑戰',
    highAchievement: '高成就感',
    topChallenge: '頂級挑戰',
    highestAchievement: '最高成就感',
    selectDifficulty: '選擇難度',
    startDopamineChallenge: '開始挑戰',
    challengeYourLimits: '挑戰極限',
    userLimited: '用戶限定',
    beyondNormalMode: '超越普通模式',
    modeFeatures: '模式特色',
    selectChallengeDifficulty: '選擇挑戰難度',
    chooseDifficultyChallenge: '選擇難度挑戰，專注於特定難度',
    specialScoringSystem: '特殊計分系統，連擊與速度獎勵',
    timeLimitChallenge: '時間限制內完成數獨挑戰',
    errorCountAffectsScore: '錯誤次數影響最終分數',
    consecutiveCorrectReward: '連續正確填寫可獲得連擊獎勵',
    speedCompletionBonus: '完成速度越快，分數加成越高',
    challengeFailed: '挑戰失敗',
    dopamineAchievementWall: '多巴胺成就牆',
    noTopScoreData: '暫無最高分數據',
    difficultyLevel: '難度等級',
    againChallenge: '再次挑戰',
    returnToMainMenu: '返回主選單',
    congratulationsComplete: '恭喜完成',
    successfullyCompletedGame: '您成功完成了遊戲',
    currentRank: '目前排名',
    totalScore: '總分數',
    newRecord: '新紀錄！',
    completionTime: '完成時間',
    errorCount: '錯誤次數',
    playAgain: '再玩一次',
    viewLeaderboardButton: '查看排行榜',
    congratulations: '恭喜',
    remainingTime: '剩餘時間',
    maxCombo: '最大連擊',
    
    // 排行榜
    leaderboard: '排行榜',
    viewLeaderboard: '查看排行榜',
    viewHighestScore: '查看最高分',
    all: '全部',
    gamesPlayed: '場遊戲',
    achievementWall: '成就牆',
    noData: '暫無成就資料',
    highestScoreDisplay: '最高分展示',
    
    // 用戶相關
    welcome: '歡迎',
    viewStats: '查看統計',
    normal: '普通',
    dopamine: '多巴胺',
    
    // 通用
    close: '關閉',
    back: '返回',
    restart: '再次挑戰',
    returnToMain: '返回主選單',
    
    // 主題
    currentTheme: '當前主題',
    clickToToggle: '點擊切換明暗模式',
    
    // 載入狀態
    loadingStats: '載入統計中...',
    
    // 用戶統計
    bestScore: '最佳分數',
    bestTime: '最佳時間',
    totalGames: '總遊戲數',
    
    // 遊戲規則
    scoringSystem: '計分系統',
    rules: '規則',
    scoring: '計分',
    tips: '解題技巧',
    basicRules: '基本規則',
    killerSudokuFeatures: '殺手數獨特色',
    solvingStrategy: '解題策略',
    uniqueCandidate: '唯一候選數',
    hiddenSingle: '隱藏單數',
    killerSudokuTips: '殺手數獨技巧',
    speedImprovement: '速度提升',
    leaderboardDescription: '排行榜按難度分類，顯示各難度的最佳成績',
    rankingCriteria: '排名依據：分數 → 最佳時間 → 遊戲次數',
    autoUpdate: '每次完成遊戲都會自動更新排行榜',
    transparentScoring: '分數計算過程會完整記錄，確保公平透明',
    basicScore: '基礎分數',
    timeBonus: '時間獎勵',
    mistakePenalty: '錯誤懲罰',
    calculationFormula: '計算公式',
    finalScoreFormula: '最終分數 = max(基礎分數 × 0.2, 基礎分數 + 時間獎勵 - 錯誤懲罰)',
    idealTime: '理想時間',
    earlyBonus: '提前',
    overtimePenalty: '超時',
    mistake: '錯誤',
    minimumScore: '最低分數',
    example: '範例',
    points: '分',
    minutes: '分',
    basicRulesDescription: '在9×9的格子中填入數字1-9，每行、每列、每個3×3宮格都不能重複。',
    killerSudokuFeaturesDescription: '虛線框內的數字必須相加等於左上角的數字，且框內數字不能重複。',
    solvingStrategyDescription: '先從只有一個可能數字的格子開始，逐步推理其他格子的數字。',
    uniqueCandidateDescription: '在行、列或宮格中，如果某個數字只有一個可能位置，那就是答案。',
    hiddenSingleDescription: '在某個格子中，如果只有一個數字可以填入，那就是答案。',
    killerSudokuTipsDescription: '利用虛線框的總和限制，排除不可能的數字組合。',
    speedImprovementDescription: '熟練後可以同時考慮多個限制條件，提高解題速度。',
    earlyBonusDescription: '每提前1秒+0.5分（最多500分）',
    overtimePenaltyDescription: '每超時1秒-0.1分（最少0分）',
    idealTimeDescription: '簡6分、中12分、難18分、專24分',
    mistakePenaltyDescription: '每個錯誤扣除20分',
    minimumScoreDescription: '基礎分數的20%',
    minimumScoreExamples: '（簡20分、中40分、難60分、專100分）',
    scoringExample: '簡單模式，2分鐘完成，1次錯誤 = 100 + 240 - 20 = 320分',
  },
  ko: {
    // 遊戲相關
    gameTitle: '킬러 스도쿠',
    newGame: '새 게임',
    gameRules: '게임 규칙',
    difficulty: '난이도',
    easy: '쉬움',
    medium: '보통',
    hard: '어려움',
    expert: '전문가',
    hell: '지옥',
    
    // 多巴胺 모드
    dopamineMode: '도파민 모드',
    startChallenge: '도전 시작',
    remaining: '남은',
    score: '점수',
    combo: 'COMBO',
    
    // 도파민 정보 카드
    dopamineInfoTitle: '도파민 모드',
    dopamineInfoSubtitle: '한계에 도전하세요!',
    dopamineFeatures: '모드 특징',
    dopamineRules: '게임 규칙',
    basicAchievement: '기본 성취감',
    moderateChallenge: '적당한 도전',
    highAchievement: '높은 성취감',
    topChallenge: '최고 도전',
    highestAchievement: '최고 성취감',
    selectDifficulty: '난이도 선택',
    startDopamineChallenge: '도전 시작',
    challengeYourLimits: '한계에 도전',
    userLimited: '사용자 제한',
    beyondNormalMode: '일반 모드 초월',
    modeFeatures: '모드 특징',
    selectChallengeDifficulty: '도전 난이도 선택',
    chooseDifficultyChallenge: '난이도 도전 선택, 특정 난이도에 집중',
    specialScoringSystem: '특별 점수 시스템, 콤보와 속도 보상',
    timeLimitChallenge: '시간 제한 내에 스도쿠 도전 완료',
    errorCountAffectsScore: '오류 횟수가 최종 점수에 영향',
    consecutiveCorrectReward: '연속 정확한 입력으로 콤보 보상 획득',
    speedCompletionBonus: '완료 속도가 빠를수록 높은 점수 보너스',
    challengeFailed: '도전 실패',
    dopamineAchievementWall: '도파민 성취 벽',
    noTopScoreData: '최고 점수 데이터 없음',
    difficultyLevel: '난이도 레벨',
    againChallenge: '다시 도전',
    returnToMainMenu: '메인 메뉴로 돌아가기',
    congratulationsComplete: '축하합니다 완료',
    successfullyCompletedGame: '게임을 성공적으로 완료했습니다',
    currentRank: '현재 순위',
    totalScore: '총 점수',
    newRecord: '새 기록!',
    completionTime: '완료 시간',
    errorCount: '오류 횟수',
    playAgain: '다시 플레이',
    viewLeaderboardButton: '리더보드 보기',
    congratulations: '축하합니다',
    remainingTime: '남은 시간',
    maxCombo: '최대 콤보',
    
    // 리더보드
    leaderboard: '리더보드',
    viewLeaderboard: '리더보드 보기',
    viewHighestScore: '최고 점수 보기',
    all: '전체',
    gamesPlayed: '게임',
    achievementWall: '성취 벽',
    noData: '데이터 없음',
    highestScoreDisplay: '최고 점수 표시',
    
    // 사용자 관련
    welcome: '환영합니다',
    viewStats: '통계 보기',
    normal: '일반',
    dopamine: '도파민',
    
    // 일반
    close: '닫기',
    back: '뒤로',
    restart: '다시 도전',
    returnToMain: '메인 메뉴로',
    
    // 테마
    currentTheme: '현재 테마',
    clickToToggle: '라이트/다크 모드 전환',
    
    // 로딩 상태
    loadingStats: '통계 로딩 중...',
    
    // 사용자 통계
    bestScore: '최고 점수',
    bestTime: '최고 시간',
    totalGames: '총 게임 수',
    
    // 게임 규칙
    scoringSystem: '점수 시스템',
    rules: '규칙',
    scoring: '점수',
    tips: '해결 팁',
    basicRules: '기본 규칙',
    killerSudokuFeatures: '킬러 스도쿠 특징',
    solvingStrategy: '해결 전략',
    uniqueCandidate: '유일 후보수',
    hiddenSingle: '숨겨진 단수',
    killerSudokuTips: '킬러 스도쿠 팁',
    speedImprovement: '속도 향상',
    leaderboardDescription: '난이도별 순위표, 각 난이도의 최고 점수 표시',
    rankingCriteria: '순위 기준: 점수 → 최고 시간 → 게임 횟수',
    autoUpdate: '게임 완료 후 순위표 자동 업데이트',
    transparentScoring: '점수 계산 과정 완전 기록으로 공정성과 투명성 보장',
    basicScore: '기본 점수',
    timeBonus: '시간 보너스',
    mistakePenalty: '실수 페널티',
    calculationFormula: '계산 공식',
    finalScoreFormula: '최종 점수 = max(기본 점수 × 0.2, 기본 점수 + 시간 보너스 - 실수 페널티)',
    idealTime: '이상 시간',
    earlyBonus: '조기 완료',
    overtimePenalty: '시간 초과',
    mistake: '실수',
    minimumScore: '최소 점수',
    example: '예시',
    points: '점',
    minutes: '분',
    basicRulesDescription: '9×9 격자에 1-9 숫자를 채우세요. 각 행, 열, 3×3 박스는 고유한 숫자를 포함해야 합니다.',
    killerSudokuFeaturesDescription: '점선 상자 안의 숫자는 왼쪽 상단 숫자의 합과 같아야 하며, 상자 내에서 반복될 수 없습니다.',
    solvingStrategyDescription: '가능한 숫자가 하나뿐인 셀부터 시작하여 다른 셀을 점진적으로 추론하세요.',
    uniqueCandidateDescription: '행, 열 또는 박스에서 숫자가 하나의 가능한 위치만 있다면 그것이 답입니다.',
    hiddenSingleDescription: '셀에 하나의 숫자만 넣을 수 있다면 그것이 답입니다.',
    killerSudokuTipsDescription: '점선 상자의 합 제약을 활용하여 불가능한 숫자 조합을 제거하세요.',
    speedImprovementDescription: '연습을 통해 여러 제약을 동시에 고려하여 해결 속도를 향상시키세요.',
    earlyBonusDescription: '1초당 +0.5점 조기 완료 (최대 500점)',
    overtimePenaltyDescription: '1초당 -0.1점 시간 초과 (최소 0점)',
    idealTimeDescription: '쉬움 6분, 보통 12분, 어려움 18분, 전문가 24분',
    mistakePenaltyDescription: '실수당 20점 차감',
    minimumScoreDescription: '기본 점수의 20%',
    minimumScoreExamples: '(쉬움 20점, 보통 40점, 어려움 60점, 전문가 100점)',
    scoringExample: '쉬움 모드, 2분 완료, 1회 실수 = 100 + 240 - 20 = 320점',
  },
  ja: {
    // ゲーム関連
    gameTitle: 'キラー数独',
    newGame: '新しいゲーム',
    gameRules: 'ゲームルール',
    difficulty: '難易度',
    easy: '初級',
    medium: '中級',
    hard: '上級',
    expert: '達人級',
    hell: '地獄級',
    
    // ドーパミンモード
    dopamineMode: 'ドーパミンモード',
    startChallenge: 'チャレンジ開始',
    remaining: '残り',
    score: 'スコア',
    combo: 'COMBO',
    
    // ドーパミン情報カード
    dopamineInfoTitle: 'ドーパミンモード',
    dopamineInfoSubtitle: '限界に挑戦しよう！',
    dopamineFeatures: 'モード特徴',
    dopamineRules: 'ゲームルール',
    basicAchievement: '基本達成感',
    moderateChallenge: '適度な挑戦',
    highAchievement: '高い達成感',
    topChallenge: '最高挑戦',
    highestAchievement: '最高達成感',
    selectDifficulty: '難易度選択',
    startDopamineChallenge: 'チャレンジ開始',
    challengeYourLimits: '限界に挑戦',
    userLimited: 'ユーザー限定',
    beyondNormalMode: '通常モードを超越',
    modeFeatures: 'モード特徴',
    selectChallengeDifficulty: 'チャレンジ難易度選択',
    chooseDifficultyChallenge: '難易度チャレンジ選択、特定の難易度に集中',
    specialScoringSystem: '特別スコアシステム、コンボとスピード報酬',
    timeLimitChallenge: '時間制限内に数独チャレンジ完了',
    errorCountAffectsScore: 'エラー回数が最終スコアに影響',
    consecutiveCorrectReward: '連続正解入力でコンボ報酬獲得',
    speedCompletionBonus: '完了速度が速いほど高いスコアボーナス',
    challengeFailed: 'チャレンジ失敗',
    dopamineAchievementWall: 'ドーパミン実績ウォール',
    noTopScoreData: '最高スコアデータなし',
    difficultyLevel: '難易度レベル',
    againChallenge: '再チャレンジ',
    returnToMainMenu: 'メインメニューに戻る',
    congratulationsComplete: 'おめでとうございます 完了',
    successfullyCompletedGame: 'ゲームを正常に完了しました',
    currentRank: '現在のランク',
    totalScore: '総スコア',
    newRecord: '新記録！',
    completionTime: '完了時間',
    errorCount: 'エラー回数',
    playAgain: 'もう一度プレイ',
    viewLeaderboardButton: 'リーダーボードを見る',
    congratulations: 'おめでとうございます',
    remainingTime: '残り時間',
    maxCombo: '最大コンボ',
    
    // リーダーボード
    leaderboard: 'リーダーボード',
    viewLeaderboard: 'リーダーボードを見る',
    viewHighestScore: '最高スコアを見る',
    all: '全て',
    gamesPlayed: 'ゲーム',
    achievementWall: '実績ウォール',
    noData: 'データなし',
    highestScoreDisplay: '最高スコア表示',
    
    // ユーザー関連
    welcome: 'ようこそ',
    viewStats: '統計を見る',
    normal: '通常',
    dopamine: 'ドーパミン',
    
    // 一般
    close: '閉じる',
    back: '戻る',
    restart: '再挑戦',
    returnToMain: 'メインメニューに戻る',
    
    // テーマ
    currentTheme: '現在のテーマ',
    clickToToggle: 'ライト/ダークモード切り替え',
    
    // ローディング状態
    loadingStats: '統計読み込み中...',
    
    // ユーザー統計
    bestScore: '最高スコア',
    bestTime: '最高時間',
    totalGames: '総ゲーム数',
    
    // ゲームルール
    scoringSystem: 'スコアシステム',
    rules: 'ルール',
    scoring: 'スコア',
    tips: '解法のコツ',
    basicRules: '基本ルール',
    killerSudokuFeatures: 'キラー数独の特徴',
    solvingStrategy: '解法戦略',
    uniqueCandidate: '唯一候補数',
    hiddenSingle: '隠れた単数',
    killerSudokuTips: 'キラー数独のコツ',
    speedImprovement: '速度向上',
    leaderboardDescription: '難易度別ランキング、各難易度の最高スコア表示',
    rankingCriteria: 'ランキング基準：スコア → 最高時間 → ゲーム回数',
    autoUpdate: 'ゲーム完了後ランキング自動更新',
    transparentScoring: 'スコア計算過程完全記録で公平性と透明性を保証',
    basicScore: '基本スコア',
    timeBonus: '時間ボーナス',
    mistakePenalty: 'ミスペナルティ',
    calculationFormula: '計算式',
    finalScoreFormula: '最終スコア = max(基本スコア × 0.2, 基本スコア + 時間ボーナス - ミスペナルティ)',
    idealTime: '理想時間',
    earlyBonus: '早期完了',
    overtimePenalty: '時間超過',
    mistake: 'ミス',
    minimumScore: '最低スコア',
    example: '例',
    points: '点',
    minutes: '分',
    basicRulesDescription: '9×9のグリッドに1-9の数字を埋めてください。各行、列、3×3ボックスは一意の数字を含む必要があります。',
    killerSudokuFeaturesDescription: '破線ボックス内の数字は左上の数字の合計と等しく、ボックス内で重複してはいけません。',
    solvingStrategyDescription: '可能な数字が1つしかないセルから始めて、他のセルを段階的に推論してください。',
    uniqueCandidateDescription: '行、列、またはボックスで数字が1つの可能な位置しかない場合、それが答えです。',
    hiddenSingleDescription: 'セルに1つの数字しか入れられない場合、それが答えです。',
    killerSudokuTipsDescription: '破線ボックスの合計制約を活用して、不可能な数字の組み合わせを排除してください。',
    speedImprovementDescription: '練習により複数の制約を同時に考慮して、解決速度を向上させてください。',
    earlyBonusDescription: '1秒あたり+0.5点早期完了（最大500点）',
    overtimePenaltyDescription: '1秒あたり-0.1点時間超過（最小0点）',
    idealTimeDescription: '簡単6分、普通12分、困難18分、専門家24分',
    mistakePenaltyDescription: 'ミス1回につき20点減点',
    minimumScoreDescription: '基本スコアの20%',
    minimumScoreExamples: '（簡単20点、普通40点、困難60点、専門家100点）',
    scoringExample: '簡単モード、2分完了、1回ミス = 100 + 240 - 20 = 320点',
  },
};

export const useLanguage = () => {
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    // 監聽語言變更事件
    const handleLanguageChange = (event: CustomEvent) => {
      setLanguage(event.detail.language);
    };

    window.addEventListener('languageChange', handleLanguageChange as EventListener);
    
    // 初始化語言
    const savedLanguage = localStorage.getItem('killer-sudoku-language') as Language;
    if (savedLanguage && ['en', 'zh', 'ko', 'ja'].includes(savedLanguage)) {
      setLanguage(savedLanguage);
    }

    return () => {
      window.removeEventListener('languageChange', handleLanguageChange as EventListener);
    };
  }, []);

  const t = (key: keyof typeof translations.en) => {
    return translations[language][key] || translations.en[key] || key;
  };

  return { language, t };
};
