import { useState, useEffect } from 'react';
import { Language } from '@/components/LanguageToggle';

// 語言翻譯對象
const translations = {
  en: {
    // 遊戲相關
    gameTitle: 'Sudoku',
    newGame: 'New Game',
    gameRules: 'Game Rules',
    difficulty: 'Difficulty',
    easy: 'EASY',
    medium: 'MID',
    hard: 'HARD',
    expert: 'XPR',
    hell: 'HELL',

    // Theme & Language
    theme: 'Theme',
    mode: 'Mode',
    themeLight: 'Light',
    themeDark: 'Dark',
    language: 'Language',
    login: 'Login',
    logout: 'Logout',

    // 多巴胺模式
    dopamineMode: 'Dopamine Mode',
    startChallenge: 'Start Challenge',
    remaining: 'Remaining',
    score: 'Score',
    combo: 'COMBO',

    // 註解功能
    showNotes: 'Show Notes',
    hideNotes: 'Hide Notes',
    notes: 'Notes',
    notesOn: 'Notes ON',
    notesOff: 'Notes OFF',
    notesModeOn: 'Enable Notes Mode',
    notesModeOff: 'Disable Notes Mode',
    candidateNumbers: 'Candidate Numbers',

    // 提示功能
    hint: 'Hint',
    hintCountUsedUp: 'Hint count used up',

    // 遊戲控制
    clickToResume: 'Click to resume',
    clickToPause: 'Click to pause',
    dopamineModeVisitorOnly: 'Dopamine Mode - Registered users only',

    // 其他
    githubRepository: 'GitHub Repository',

    // 多巴胺資訊卡
    dopamineInfoTitle: 'Dopamine Mode',
    dopamineInfoSubtitle: 'Challenge Your Limits!',
    dopamineFeatures: 'Mode Features',
    dopamineRules: 'Game Rules',
    basicAchievement: 'Basic Achievement',
    moderateChallenge: 'Moderate Challenge',
    highAchievement: 'High Achievement',
    topChallenge: 'Top Challenge',
    highestAchievement: 'Highest Achievement',
    selectDifficulty: 'Select Difficulty',
    startDopamineChallenge: 'Start Challenge',
    challengeYourLimits: 'Challenge Your Limits',

    beyondNormalMode: 'Beyond Normal Mode',
    modeFeatures: 'Mode Features',
    selectChallengeDifficulty: 'Select Challenge Difficulty',
    chooseDifficultyChallenge: 'Choose difficulty challenge, focus on specific difficulty',
    specialScoringSystem: 'Special scoring system, combo and speed rewards',
    timeLimitChallenge: 'Complete sudoku challenge within time limit',
    errorCountAffectsScore: 'Error count affects final score',
    consecutiveCorrectReward: 'Consecutive correct filling can get combo reward',
    speedCompletionBonus: 'Faster completion gives higher score bonus',
    challengeFailed: 'Challenge Failed',
    dopamineAchievementWall: 'Dopamine Achievement Wall',
    noTopScoreData: 'No Top Score Data',
    difficultyLevel: 'Difficulty Level',
    againChallenge: 'Challenge Again',
    returnToMainMenu: 'Return to Main Menu',
    congratulationsComplete: 'Congratulations Complete',
    successfullyCompletedGame: 'You have successfully completed the game',
    currentRank: 'Current Rank',
    totalScore: 'Total Score',
    newRecord: 'New Record!',
    completionTime: 'Completion Time',
    errorCount: 'Error Count',
    playAgain: 'Play Again',
    viewLeaderboardButton: 'View Leaderboard',
    congratulations: 'Congratulations',
    remainingTime: 'Remaining Time',
    maxCombo: 'Max Combo',

    // 排行榜
    leaderboard: 'World Ranking',

    viewLeaderboard: 'View Leaderboard',
    viewHighestScore: 'View Highest Score',
    all: 'All',
    gamesPlayed: 'Games Played',
    achievementWall: 'Achievement Wall',
    noData: 'No Data',
    highestScoreDisplay: 'Highest Score Display',
    leaderboardPageTitle: 'Leaderboard',
    highestScoreTitle: 'Highest Score Showcase',
    backToGame: 'Back to Game',

    // 用戶相關
    welcome: 'Welcome',
    welcomeToKillerSudoku: 'Welcome to Sudoku',
    enterNameToStart: 'Please enter your name to start playing and participate in the leaderboard',
    welcomeUser: 'Welcome, ',

    // User Status
    userStatusTitle: 'User Status',
    userStatusDesc: 'Your game data is saved locally',
    nameLabel: 'Name',
    userIdLabel: 'User ID',
    joinDateLabel: 'Joined',
    unknownDate: 'Unknown',
    switchUser: 'Switch User',

    enterYourName: 'Please enter your name',
    processing: 'Processing...',
    startGame: 'Start Game',
    visitorMode: 'Visitor Mode',
    visitorModeDescription: 'Visitor mode does not score and does not participate in leaderboard',
    checkNetworkConnection: 'Please check your network connection or try again later. If the problem persists, please contact the administrator.',
    usernameAlreadyExists: 'Username already exists, please enter a different name',
    viewStats: 'View Stats',
    normal: 'Normal',
    dopamine: 'Dopamine',

    // 通用
    close: 'Close',
    back: 'Back',
    restart: 'Restart',
    returnToMain: 'Return to Main Menu',
    clear: 'Clear',

    // 主題
    currentTheme: 'Current theme',
    clickToToggle: 'Click to toggle between light and dark',

    // 載入狀態
    loadingStats: 'Loading stats...',

    // 用戶統計
    bestScore: 'Best Score',
    bestTime: 'Best Time',
    totalGames: 'Total Games',
    playerHub: 'Player Hub',
    myStats: 'My Stats',

    // Table Headers
    colPlayer: 'Player',
    colDifficulty: 'Difficulty',
    colGames: 'Games',
    colTime: 'Time',
    colScore: 'Score',
    top50: 'Top 50',

    pleaseRegister: 'Register to Play',

    // Dopamine Mode
    registerToUnlock: 'Register to Unlock More!',
    exclusiveFeature: 'Exclusive Feature',
    comboRewardSystem: 'Combo Reward System',
    hellDifficulty: 'Hell Difficulty',
    exclusiveLeaderboard: 'Exclusive Leaderboard',
    globalLeaderboardCompetition: 'Global Leaderboard Competition',
    competeWithGlobal: 'Compete with Global Players',
    rankByDifficulty: 'Rank by Difficulty',
    personalBest: 'Personal Best',
    permanentRecord: 'Permanent Record',
    howToRegister: 'How to Register?',
    enterUsername: 'Enter Username',
    chooseUniqueName: 'Choose a unique username',
    startPlayingNow: 'Start Playing Now',
    noComplexVerification: 'No complex verification required',
    dataAutoSync: 'Data Auto Sync',
    recordSavedToCloud: 'Game records automatically saved to cloud',
    becomeRegisteredUser: 'Become a Registered User',
    continueAsGuest: 'Continue as Guest',

    userLimited: 'User Exclusive',



    // 遊戲規則
    scoringSystem: 'Scoring System',
    rules: 'Rules',
    scoring: 'Scoring',
    tips: 'Tips',
    basicRules: 'Basic Rules',
    killerSudokuFeatures: 'Killer Sudoku Features',
    solvingStrategy: 'Solving Strategy',
    uniqueCandidate: 'Unique Candidate',
    hiddenSingle: 'Hidden Single',
    killerSudokuTips: 'Killer Sudoku Tips',
    speedImprovement: 'Speed Improvement',
    leaderboardDescription: 'Leaderboard by difficulty, showing best scores for each difficulty',
    rankingCriteria: 'Ranking criteria: Score → Best Time → Games Played',
    autoUpdate: 'Leaderboard updates automatically after each game completion',
    transparentScoring: 'Complete scoring process recording ensures fairness and transparency',
    basicScore: 'Basic Score',
    timeBonus: 'Time Bonus',
    mistakePenalty: 'Mistake Penalty',
    calculationFormula: 'Calculation Formula',
    finalScoreFormula: 'Final Score = max(Basic Score × 0.2, Basic Score + Time Bonus - Mistake Penalty)',
    idealTime: 'Ideal Time',
    earlyBonus: 'Early',
    overtimePenalty: 'Overtime',
    mistake: 'Mistake',
    mistakes: 'Mistakes',

    minimumScore: 'Minimum Score',
    example: 'Example',
    points: 'pts',
    minutes: 'min',
    basicRulesDescription: 'Fill numbers 1-9 in a 9×9 grid. Each row, column, and 3×3 box must contain unique numbers.',
    killerSudokuFeaturesDescription: 'Numbers in dashed boxes must sum to the number in the top-left corner, and cannot repeat within the box.',
    solvingStrategyDescription: 'Start with cells that have only one possible number, then gradually deduce other cells.',
    uniqueCandidateDescription: 'If a number has only one possible position in a row, column, or box, that\'s the answer.',
    hiddenSingleDescription: 'If only one number can be placed in a cell, that\'s the answer.',
    killerSudokuTipsDescription: 'Use the sum constraints of dashed boxes to eliminate impossible number combinations.',
    speedImprovementDescription: 'With practice, consider multiple constraints simultaneously to improve solving speed.',
    earlyBonusDescription: '+0.5 points per second early (max 500 points)',
    overtimePenaltyDescription: '-0.1 points per second overtime (min 0 points)',
    idealTimeDescription: 'EASY 6min, MID 12min, HARD 18min, XPR 24min',
    mistakePenaltyDescription: '20 points deducted per mistake',
    minimumScoreDescription: '20% of basic score',
    minimumScoreExamples: '(EASY 20pts, MID 40pts, HARD 60pts, XPR 100pts)',
    scoringExample: 'EASY mode, 2 minutes, 1 mistake = 100 + 240 - 20 = 320 points',

    // SEO 相關
    app_title: 'Killer Sudoku - Free Online Puzzle Game | Killer Sudoku Puzzle Game',
    app_description: 'Free Killer Sudoku game! 5 difficulty levels, dopamine mode, global leaderboard. No download required, play now! Perfect for students, office workers, and seniors.',
    app_keywords: 'killer sudoku,sudoku,puzzle game,free game,online game,sudoku game,free puzzle game,brain game,dopamine sudoku,leaderboard,english,sudoku challenge,sudoku puzzle,free puzzle,brain training',
    app_name: 'Killer Sudoku',
    game_category: 'Puzzle Game',
    game_genre: 'Sudoku',
    game_platform: 'Web Game',
    audience_type: 'Students, Office Workers, Seniors',
    game_image_alt: 'Killer Sudoku Game Screenshot',
    og_locale: 'en_US',

    // Footer Legal Links
    footer: {
      about: 'About Us',
      howToPlay: 'How to Play',
      strategy: 'Strategy',
      terms: 'Terms',
      privacy: 'Privacy',
      cookies: 'Cookie',
      contact: 'Contact',
    },

    // Content Pages
    about: {
      seoTitle: 'About Killer Sudoku - The Best Online Puzzle Game',
      seoDescription: 'Learn about Killer Sudoku, our mission to provide the best free online puzzle experience, and why you should choose us for your daily brain training.',
      title: 'About Us',
      backToGame: 'Back to Game',
      whatWeDo: {
        title: 'What We Do',
        p1: 'We are dedicated to providing the best online Killer Sudoku experience for players of all levels. Our platform combines classic sudoku rules with arithmetic challenges to create a unique and engaging puzzle game.',
        p2: 'Whether you are a beginner looking to learn the ropes or an expert seeking a challenge, our game offers various difficulty levels and modes to suit your needs.',
      },
      whyUs: {
        title: 'Why Choose Us?',
        li1: 'Free to play with no downloads required',
        li2: 'Multiple difficulty levels from Easy to Hell',
        li3: 'Unique Dopamine Mode for fast-paced fun',
        li4: 'Global leaderboard to compete with players worldwide',
      },
      contact: {
        title: 'Contact Us',
        p1: 'Have questions or feedback? We would love to hear from you. Visit our Contact page to get in touch.',
      },
    },
    howToPlay: {
      seoTitle: 'How to Play Killer Sudoku - Rules and Tips',
      seoDescription: 'Master the rules of Killer Sudoku with our comprehensive guide. Learn basic rules, scoring system, and tips to solve puzzles faster.',
      title: 'How to Play',
      backToGame: 'Back to Game',
      rules: {
        title: 'Game Rules',
        li1: 'Fill the grid with numbers 1-9 so that each row, column, and 3x3 box contains all digits exactly once.',
        li2: 'The grid is divided into cages (dashed lines). The sum of numbers in a cage must equal the small number in its top-left corner.',
        li3: 'Numbers cannot repeat within a cage.',
      },
      tips: {
        title: 'Tips for Success',
        li1: 'Start with cages that have only one possible combination (e.g., a 2-cell cage with sum 3 must be 1 and 2).',
        li2: 'Use the Rule of 45: The sum of numbers in any row, column, or 3x3 box is always 45.',
        li3: 'Look for "innies" and "outies" by comparing cage sums with the Rule of 45.',
      },
      scoring: {
        title: 'Scoring System',
        p1: 'Your score is calculated based on difficulty, completion time, and mistakes. In Dopamine Mode, you also get bonuses for speed and combos!',
      },
    },
    strategy: {
      seoTitle: 'Killer Sudoku Strategy - Advanced Techniques',
      seoDescription: 'Improve your Killer Sudoku skills with our strategy guide. Learn advanced techniques, common mistakes to avoid, and how to solve expert puzzles.',
      title: 'Strategy Guide',
      backToGame: 'Back to Game',
      common: {
        title: 'Common Strategies',
        li1: 'Scan for unique sums: Some cage sums have only one possible combination of numbers.',
        li2: 'The 45 Rule: Use the fact that every row, column, and box sums to 45 to deduce numbers in cages that cross boundaries.',
        li3: 'Cage Combinations: Memorize common sums for 2, 3, or 4 cells to speed up your solving.',
        li4: 'Pencil Marks: Use notes to keep track of possible candidates for each cell.',
      },
      advanced: {
        title: 'Advanced Tactics',
        li1: 'Innies and Outies: Calculate the difference between a cage sum and 45 to find numbers inside or outside a region.',
        li2: 'Split Cages: Break down complex cages into smaller, manageable parts.',
        li3: 'Parity Analysis: Sometimes knowing if a number is odd or even can help eliminate possibilities.',
      },
      mistakes: {
        title: 'Common Mistakes',
        li1: 'Guessing: Never guess. Always use logic to deduce the next number.',
        li2: 'Ignoring Constraints: Remember to check row, column, and box constraints in addition to cage sums.',
        li3: 'Rushing: Take your time to analyze the board, especially in higher difficulties.',
      },
    },

    // Legal Documents
    legal: {
      privacyPolicy: {
        title: 'Privacy Policy',
        lastUpdated: 'Last updated: January 1, 2025',
        introduction: 'This Privacy Policy describes how Killer Sudoku Score ("we", "our", or "us") collects, uses, and protects your information when you use our web application.',
        informationCollection: 'Information We Collect',
        informationCollectionContent: 'We collect minimal information necessary to provide our service: username (for leaderboard participation), game statistics (scores, completion times), and technical data (browser type, device information).',
        informationUse: 'How We Use Your Information',
        informationUseContent: 'Your information is used solely to: provide game functionality, maintain leaderboards, improve user experience, and ensure service security. We do not sell or share your personal data with third parties.',
        dataStorage: 'Data Storage and Security',
        dataStorageContent: 'Your data is stored securely using industry-standard encryption. We implement appropriate technical and organizational measures to protect against unauthorized access, alteration, disclosure, or destruction.',
        cookies: 'Cookies and Local Storage',
        cookiesContent: 'We use cookies and local storage to remember your preferences, game progress, and language settings. You can disable cookies in your browser settings, though this may affect functionality.',
        userRights: 'Your Rights',
        userRightsContent: 'You have the right to access, update, or delete your personal data. Contact us to exercise these rights. You can also opt out of leaderboard participation by using visitor mode.',
        changes: 'Changes to This Policy',
        changesContent: 'We may update this Privacy Policy periodically. We will notify users of significant changes through our application or website.',
        contact: 'Contact Information',
        contactContent: 'If you have questions about this Privacy Policy, please contact us through our contact page.',
      },
      termsOfService: {
        title: 'Terms of Service',
        lastUpdated: 'Last updated: January 1, 2025',
        acceptance: 'Acceptance of Terms',
        acceptanceContent: 'By accessing and using Killer Sudoku Score, you accept and agree to be bound by the terms and provision of this agreement.',
        serviceDescription: 'Service Description',
        serviceDescriptionContent: 'Killer Sudoku Score is a web-based puzzle game that provides sudoku challenges with scoring systems and leaderboards. The service is provided "as is" without warranties.',
        userConduct: 'User Conduct',
        userConductContent: 'Users agree to: use the service lawfully, not attempt to manipulate scores or rankings, respect other users, and not engage in harmful or disruptive behavior.',
        intellectualProperty: 'Intellectual Property',
        intellectualPropertyContent: 'All content, including game logic, design, and code, is protected by intellectual property laws. Users may not copy, modify, or distribute our content without permission.',
        privacy: 'Privacy',
        privacyContent: 'Your privacy is important to us. Please review our Privacy Policy to understand how we collect and use your information.',
        serviceAvailability: 'Service Availability',
        serviceAvailabilityContent: 'We strive to maintain service availability but cannot guarantee uninterrupted access. We reserve the right to modify or discontinue the service at any time.',
        disclaimer: 'Disclaimer',
        disclaimerContent: 'The service is provided "as is" without warranties of any kind. We do not guarantee accuracy, reliability, or availability of the service.',
        limitationOfLiability: 'Limitation of Liability',
        limitationOfLiabilityContent: 'To the maximum extent permitted by law, we shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the service.',
        termination: 'Termination',
        terminationContent: 'We may terminate or suspend your access to the service immediately, without prior notice, for any reason, including breach of these terms.',
        governingLaw: 'Governing Law',
        governingLawContent: 'These terms shall be governed by and construed in accordance with applicable laws, without regard to conflict of law principles.',
        changes: 'Changes to Terms',
        changesContent: 'We reserve the right to modify these terms at any time. Continued use of the service after changes constitutes acceptance of new terms.',
        contact: 'Contact Information',
        contactContent: 'For questions about these Terms of Service, please contact us through our contact page.',
      },
      cookiePolicy: {
        title: 'Cookie Policy',
        lastUpdated: 'Last updated: January 1, 2025',
        introduction: 'This Cookie Policy explains how Killer Sudoku Score uses cookies and similar technologies when you visit our website.',
        whatAreCookies: 'What Are Cookies',
        whatAreCookiesContent: 'Cookies are small text files stored on your device when you visit a website. They help websites remember information about your visit.',
        howWeUseCookies: 'How We Use Cookies',
        howWeUseCookiesContent: 'We use cookies to: remember your language preferences, save game progress, maintain user sessions, and improve website functionality.',
        typesOfCookies: 'Types of Cookies We Use',
        essentialCookies: 'Essential Cookies',
        essentialCookiesContent: 'These cookies are necessary for the website to function properly. They enable basic functions like page navigation and access to secure areas.',
        preferenceCookies: 'Preference Cookies',
        preferenceCookiesContent: 'These cookies remember your choices and preferences, such as language settings and theme selection.',
        analyticsCookies: 'Analytics Cookies',
        analyticsCookiesContent: 'These cookies help us understand how visitors interact with our website by collecting anonymous information.',
        managingCookies: 'Managing Cookies',
        managingCookiesContent: 'You can control cookies through your browser settings. However, disabling cookies may affect website functionality.',
        thirdPartyCookies: 'Third-Party Cookies',
        thirdPartyCookiesContent: 'We may use third-party services that set their own cookies. Please review their privacy policies for more information.',
        updates: 'Updates to This Policy',
        updatesContent: 'We may update this Cookie Policy from time to time. Please check this page regularly for any changes.',
        contact: 'Contact Us',
        contactContent: 'If you have questions about our use of cookies, please contact us through our contact page.',
      },
      contact: {
        title: 'Contact Us',
        lastUpdated: 'Last updated: January 1, 2025',
        introduction: 'We welcome your feedback, questions, and suggestions about Killer Sudoku Score.',
        waysToContact: 'Ways to Contact Us',
        email: 'Email',
        emailContent: 'For general inquiries, technical support, or feedback, please send us an email.',
        github: 'GitHub',
        githubContent: 'For technical issues, bug reports, or feature requests, please visit our GitHub repository.',
        responseTime: 'Response Time',
        responseTimeContent: 'We aim to respond to all inquiries within 48 hours during business days.',
        typesOfInquiries: 'Types of Inquiries We Handle',
        technicalSupport: 'Technical Support',
        technicalSupportContent: 'Issues with game functionality, browser compatibility, or performance problems.',
        privacyConcerns: 'Privacy Concerns',
        privacyConcernsContent: 'Questions about data collection, usage, or privacy policy.',
        featureRequests: 'Feature Requests',
        featureRequestsContent: 'Suggestions for new features or improvements to existing functionality.',
        bugReports: 'Bug Reports',
        bugReportsContent: 'Reports of errors, glitches, or unexpected behavior in the game.',
        feedback: 'General Feedback',
        feedbackContent: 'Comments, suggestions, or general feedback about the game experience.',
        beforeContacting: 'Before Contacting Us',
        beforeContactingContent: 'Please check our FAQ section and ensure you are using the latest version of your browser. Many issues can be resolved by clearing browser cache or updating your browser.',
        privacyNote: 'Privacy Note',
        privacyNoteContent: 'When contacting us, please do not include sensitive personal information unless necessary. We will only use your information to respond to your inquiry.',
        businessHours: 'Business Hours',
        businessHoursContent: 'We typically respond to inquiries Monday through Friday, 9 AM to 5 PM (UTC).',
      },
    },
  },
  zh: {
    // 遊戲相關
    gameTitle: '殺手數獨',
    newGame: '新遊戲',
    gameRules: '遊戲規則',
    difficulty: '難度',
    easy: '簡單',
    medium: '中等',
    hard: '困難',
    expert: '專家',
    hell: '地獄',

    // Theme & Language
    theme: '主題',
    mode: '模式',
    themeLight: '亮色',
    themeDark: '暗色',
    language: '語言',
    login: '登入',
    logout: '登出',

    // 多巴胺模式
    dopamineMode: '多巴胺模式',
    startChallenge: '開始挑戰',
    remaining: '剩餘',
    score: '分數',
    combo: 'COMBO',

    // 註解功能
    showNotes: '顯示註解',
    hideNotes: '隱藏註解',
    notes: '註解',
    notesOn: '註解開',
    notesOff: '註解關',
    notesModeOn: '開啟註解模式',
    notesModeOff: '關閉註解模式',
    candidateNumbers: '候選數字',

    // 提示功能
    hint: '提示',
    hintCountUsedUp: '提示次數已用完',

    // 遊戲控制
    clickToResume: '點擊繼續',
    clickToPause: '點擊暫停',
    dopamineModeVisitorOnly: '多巴胺模式 - 註冊用戶專屬功能',

    // 其他
    githubRepository: 'GitHub 儲存庫',

    // 多巴胺資訊卡
    dopamineInfoTitle: '多巴胺模式',
    dopamineInfoSubtitle: '挑戰你的極限！',
    dopamineFeatures: '模式特色',
    dopamineRules: '遊戲規則',
    basicAchievement: '基礎成就感',
    moderateChallenge: '適度挑戰',
    highAchievement: '高成就感',
    topChallenge: '頂級挑戰',
    highestAchievement: '最高成就感',
    selectDifficulty: '選擇難度',
    startDopamineChallenge: '開始挑戰',
    challengeYourLimits: '挑戰極限',
    userLimited: '用戶限定',
    beyondNormalMode: '超越普通模式',
    modeFeatures: '模式特色',
    selectChallengeDifficulty: '選擇挑戰難度',
    chooseDifficultyChallenge: '選擇難度挑戰，專注於特定難度',
    specialScoringSystem: '特殊計分系統，連擊與速度獎勵',
    timeLimitChallenge: '時間限制內完成數獨挑戰',
    errorCountAffectsScore: '錯誤次數影響最終分數',
    consecutiveCorrectReward: '連續正確填寫可獲得連擊獎勵',
    speedCompletionBonus: '完成速度越快，分數加成越高',
    challengeFailed: '挑戰失敗',
    dopamineAchievementWall: '多巴胺成就牆',
    noTopScoreData: '暫無最高分數據',
    difficultyLevel: '難度等級',
    againChallenge: '再次挑戰',
    returnToMainMenu: '返回主選單',
    congratulationsComplete: '恭喜完成',
    successfullyCompletedGame: '您成功完成了遊戲',
    currentRank: '目前排名',
    totalScore: '總分數',
    newRecord: '新紀錄！',
    completionTime: '完成時間',
    errorCount: '錯誤次數',
    playAgain: '再玩一次',
    viewLeaderboardButton: '查看排行榜',
    congratulations: '恭喜',
    remainingTime: '剩餘時間',
    maxCombo: '最大連擊',

    // 排行榜
    leaderboard: '世界排名',

    viewLeaderboard: '查看排行榜',
    viewHighestScore: '查看最高分',
    all: '全部',
    gamesPlayed: '場遊戲',
    achievementWall: '成就牆',
    noData: '暫無成就資料',
    highestScoreDisplay: '最高分展示',
    leaderboardPageTitle: '排行榜',
    highestScoreTitle: '最高分展示',
    backToGame: '返回遊戲',

    // 用戶相關
    welcome: '歡迎',
    welcomeToKillerSudoku: '歡迎來到殺手數獨',
    enterNameToStart: '請輸入您的名稱以開始遊戲並參與排行榜',
    welcomeUser: '歡迎，',

    // User Status
    userStatusTitle: '用戶狀態',
    userStatusDesc: '您的遊戲資料已儲存在本地',
    nameLabel: '姓名',
    userIdLabel: '用戶 ID',
    joinDateLabel: '加入時間',
    unknownDate: '未知',
    switchUser: '切換用戶',

    enterYourName: '請輸入您的名稱',
    processing: '處理中...',
    startGame: '開始遊戲',
    visitorMode: '訪客模式',
    visitorModeDescription: '訪客模式不計分，不參與排行榜',
    checkNetworkConnection: '請檢查網路連接或稍後再試。如果問題持續，請聯繫管理員。',
    usernameAlreadyExists: '用戶名稱已註冊，請重新輸入',
    viewStats: '查看統計',
    normal: '普通',
    dopamine: '多巴胺',

    // 通用
    close: '關閉',
    back: '返回',
    restart: '再次挑戰',
    returnToMain: '返回主選單',
    clear: '清除',

    // 主題
    currentTheme: '當前主題',
    clickToToggle: '點擊切換明暗模式',

    // 載入狀態
    loadingStats: '載入統計中...',

    // 用戶統計
    bestScore: '最佳分數',
    bestTime: '最佳時間',
    totalGames: '總遊戲數',
    playerHub: '玩家中心',
    myStats: '個人戰績',
    statsMode: '統計模式',
    // Table Headers
    colDifficulty: '難度',
    colPlayer: '玩家',
    colGames: '場次',
    colTime: '時間',
    colScore: '分數',
    top50: '前 50 名',

    // Suffix Dopamine Mode Keys
    pleaseRegister: '註冊以挑戰',

    registerToUnlock: '註冊用戶，解鎖更多！',
    exclusiveFeature: '獨家功能',
    comboRewardSystem: '連擊獎勵系統',
    hellDifficulty: '魔王級地獄難度',
    exclusiveLeaderboard: '專屬計分排行榜',
    globalLeaderboardCompetition: '全球排行榜競爭',
    competeWithGlobal: '與全球玩家競爭',
    rankByDifficulty: '按難度分類排行',
    personalBest: '個人最佳成績',
    permanentRecord: '遊戲記錄永久保存',
    howToRegister: '如何成為註冊用戶？',
    enterUsername: '輸入用戶名稱',
    chooseUniqueName: '選擇獨特的用戶名稱',
    startPlayingNow: '立即開始遊戲',
    noComplexVerification: '無需複雜驗證流程',
    dataAutoSync: '數據自動同步',
    recordSavedToCloud: '遊戲記錄自動保存到雲端',
    becomeRegisteredUser: '立即成為註冊用戶',
    continueAsGuest: '繼續訪客模式',


    // 遊戲規則
    scoringSystem: '計分系統',
    rules: '規則',
    scoring: '計分',
    tips: '解題技巧',
    basicRules: '基本規則',
    killerSudokuFeatures: '殺手特色',
    solvingStrategy: '解題策略',
    uniqueCandidate: '唯一候選數',
    hiddenSingle: '隱藏單數',
    killerSudokuTips: '殺手數獨技巧',
    speedImprovement: '速度提升',
    leaderboardDescription: '排行榜按難度分類，顯示各難度的最佳成績',
    rankingCriteria: '排名依據：分數 → 最佳時間 → 遊戲次數',
    autoUpdate: '每次完成遊戲都會自動更新排行榜',
    transparentScoring: '分數計算過程會完整記錄，確保公平透明',
    basicScore: '基礎分數',
    timeBonus: '時間獎勵',
    mistakePenalty: '錯誤懲罰',
    calculationFormula: '計算公式',
    finalScoreFormula: '最終分數 = max(基礎分數 × 0.2, 基礎分數 + 時間獎勵 - 錯誤懲罰)',
    idealTime: '理想時間',
    earlyBonus: '提前',
    overtimePenalty: '超時',
    mistake: '錯誤',
    mistakes: '失誤',

    minimumScore: '最低分數',
    example: '範例',
    points: '分',
    minutes: '分',
    basicRulesDescription: '在格子中填入數字1-9，每行、每列、每個9宮格都不能重複。',
    killerSudokuFeaturesDescription: '虛線框內的數字必須相加等於左上角數字，框內數字不能重複。',
    solvingStrategyDescription: '先從只有一個可能數字的格子開始，逐步推理其他格子的數字。',
    uniqueCandidateDescription: '在行、列或宮格中，如果某個數字只有一個可能位置，那就是答案。',
    hiddenSingleDescription: '在某個格子中，如果只有一個數字可以填入，那就是答案。',
    killerSudokuTipsDescription: '利用虛線框的總和限制，排除不可能的數字組合。',
    speedImprovementDescription: '熟練後可以同時考慮多個限制條件，提高解題速度。',
    earlyBonusDescription: '每提前1秒+0.5分（最多500分）',
    overtimePenaltyDescription: '每超時1秒-0.1分（最少0分）',
    idealTimeDescription: '簡6分、中12分、難18分、專24分',
    mistakePenaltyDescription: '每個錯誤扣除20分',
    minimumScoreDescription: '基礎分數的20%',
    minimumScoreExamples: '（簡20分、中40分、難60分、專100分）',
    scoringExample: '簡單模式，2分鐘完成，1次錯誤 = 100 + 240 - 20 = 320分',

    // SEO 相關
    app_title: '殺手數獨 - 免費線上益智小遊戲 | Killer Sudoku 數獨遊戲',
    app_description: '免費殺手數獨遊戲！5種難度挑戰、多巴胺模式、全球排行榜。無需下載，立即遊玩！適合學生、上班族、銀髮族的益智小遊戲。',
    app_keywords: '殺手數獨,數獨,益智遊戲,免費遊戲,小遊戲,線上遊戲,數獨遊戲,免費小遊戲,益智小遊戲,多巴胺數獨,排行榜,繁體中文,數獨挑戰,數獨解謎,免費益智,腦力遊戲',
    app_name: '殺手數獨',
    game_category: '益智遊戲',
    game_genre: '數獨',
    game_platform: '網頁遊戲',
    audience_type: '學生、上班族、銀髮族',
    game_image_alt: '殺手數獨遊戲截圖',
    og_locale: 'zh_TW',

    // Footer Legal Links
    footer: {
      about: '關於我們',
      howToPlay: '玩法說明',
      strategy: '策略技巧',
      terms: '服務條款',
      privacy: '隱私政策',
      cookies: 'Cookie',
      contact: '聯絡我們',
    },

    // Content Pages
    about: {
      seoTitle: '關於殺手數獨 - 最佳線上益智遊戲',
      seoDescription: '了解殺手數獨，我們致力於提供最佳的免費線上益智體驗，以及為什麼您應該選擇我們進行日常腦力訓練。',
      title: '關於我們',
      backToGame: '返回遊戲',
      whatWeDo: {
        title: '我們做什麼',
        p1: '我們致力於為所有級別的玩家提供最佳的線上殺手數獨體驗。我們的平台結合了經典數獨規則與算術挑戰，創造出獨特且引人入勝的益智遊戲。',
        p2: '無論您是想學習入門的新手，還是尋求挑戰的專家，我們的遊戲都提供多種難度級別和模式來滿足您的需求。',
      },
      whyUs: {
        title: '為什麼選擇我們？',
        li1: '完全免費，無需下載',
        li2: '多種難度級別，從簡單到地獄',
        li3: '獨特的多巴胺模式，享受快節奏樂趣',
        li4: '全球排行榜，與世界各地玩家競爭',
      },
      contact: {
        title: '聯絡我們',
        p1: '有問題或建議嗎？我們很樂意聽取您的意見。請訪問我們的聯絡頁面與我們聯繫。',
      },
    },
    howToPlay: {
      seoTitle: '殺手數獨玩法說明 - 規則與技巧',
      seoDescription: '透過我們的完整指南掌握殺手數獨的規則。學習基本規則、計分系統以及快速解題的技巧。',
      title: '玩法說明',
      backToGame: '返回遊戲',
      rules: {
        title: '遊戲規則',
        li1: '在9x9網格中填入數字1-9，使每行、每列和每個3x3宮格都包含所有數字且不重複。',
        li2: '網格被劃分為多個虛線框。框內數字的總和必須等於左上角的小數字。',
        li3: '虛線框內的數字不能重複。',
      },
      tips: {
        title: '成功技巧',
        li1: '從只有一種可能組合的虛線框開始（例如，總和為3的2格框必須是1和2）。',
        li2: '使用45法則：任何行、列或3x3宮格的數字總和永遠是45。',
        li3: '通過比較虛線框總和與45法則，尋找「內部數」和「外部數」。',
      },
      scoring: {
        title: '計分系統',
        p1: '您的分數基於難度、完成時間和錯誤次數計算。在多巴胺模式下，您還可以獲得速度和連擊獎勵！',
      },
    },
    strategy: {
      seoTitle: '殺手數獨策略 - 進階技巧',
      seoDescription: '透過我們的策略指南提升您的殺手數獨技能。學習進階技巧、避免常見錯誤，並學會如何解決專家級謎題。',
      title: '策略指南',
      backToGame: '返回遊戲',
      common: {
        title: '常見策略',
        li1: '尋找唯一總和：某些虛線框總和只有一種可能的數字組合。',
        li2: '45法則：利用每行、每列和宮格總和為45的事實，推斷跨越邊界的虛線框中的數字。',
        li3: '虛線框組合：記住2、3或4格的常見總和，以加快解題速度。',
        li4: '鉛筆標記：使用註解來記錄每個格子可能的候選數字。',
      },
      advanced: {
        title: '進階戰術',
        li1: '內部數與外部數：計算虛線框總和與45之間的差異，找出區域內部或外部的數字。',
        li2: '拆分虛線框：將複雜的虛線框分解為更小、更易於管理的部分。',
        li3: '奇偶分析：有時知道數字是奇數還是偶數可以幫助排除可能性。',
      },
      mistakes: {
        title: '常見錯誤',
        li1: '猜測：永遠不要猜測。始終使用邏輯推斷下一個數字。',
        li2: '忽略限制：除了虛線框總和外，記得檢查行、列和宮格的限制。',
        li3: '匆忙：花時間分析盤面，特別是在較高難度下。',
      },
    },

    // 法律文件
    legal: {
      privacyPolicy: {
        title: '隱私政策',
        lastUpdated: '最後更新：2025年1月1日',
        introduction: '本隱私政策說明殺手數獨分數（「我們」、「我們的」或「本公司」）在您使用我們的網路應用程式時如何收集、使用和保護您的資訊。',
        informationCollection: '我們收集的資訊',
        informationCollectionContent: '我們僅收集提供服務所需的最少資訊：用戶名稱（用於排行榜參與）、遊戲統計資料（分數、完成時間）和技術資料（瀏覽器類型、裝置資訊）。',
        informationUse: '我們如何使用您的資訊',
        informationUseContent: '您的資訊僅用於：提供遊戲功能、維護排行榜、改善用戶體驗和確保服務安全。我們不會向第三方出售或分享您的個人資料。',
        dataStorage: '資料儲存與安全',
        dataStorageContent: '您的資料使用業界標準加密技術安全儲存。我們實施適當的技術和組織措施，防止未經授權的存取、更改、揭露或破壞。',
        cookies: 'Cookie與本地儲存',
        cookiesContent: '我們使用Cookie和本地儲存來記住您的偏好設定、遊戲進度和語言設定。您可以在瀏覽器設定中停用Cookie，但這可能會影響功能。',
        userRights: '您的權利',
        userRightsContent: '您有權存取、更新或刪除您的個人資料。請聯繫我們以行使這些權利。您也可以透過使用訪客模式選擇不參與排行榜。',
        changes: '政策變更',
        changesContent: '我們可能會定期更新此隱私政策。我們將透過我們的應用程式或網站通知用戶重大變更。',
        contact: '聯絡資訊',
        contactContent: '如果您對此隱私政策有任何疑問，請透過我們的聯絡頁面與我們聯繫。',
      },
      termsOfService: {
        title: '服務條款',
        lastUpdated: '最後更新：2025年1月1日',
        acceptance: '條款接受',
        acceptanceContent: '透過存取和使用殺手數獨分數，您接受並同意受本協議的條款和規定約束。',
        serviceDescription: '服務說明',
        serviceDescriptionContent: '殺手數獨分數是一個基於網路的益智遊戲，提供數獨挑戰、計分系統和排行榜。服務以「現狀」提供，不提供任何保證。',
        userConduct: '用戶行為',
        userConductContent: '用戶同意：合法使用服務、不嘗試操縱分數或排名、尊重其他用戶，以及不從事有害或破壞性行為。',
        intellectualProperty: '智慧財產權',
        intellectualPropertyContent: '所有內容，包括遊戲邏輯、設計和程式碼，均受智慧財產權法律保護。未經許可，用戶不得複製、修改或分發我們的內容。',
        privacy: '隱私',
        privacyContent: '您的隱私對我們很重要。請查看我們的隱私政策，了解我們如何收集和使用您的資訊。',
        serviceAvailability: '服務可用性',
        serviceAvailabilityContent: '我們努力維持服務可用性，但無法保證不間斷的存取。我們保留隨時修改或停止服務的權利。',
        disclaimer: '免責聲明',
        disclaimerContent: '服務按「現狀」提供，不提供任何形式的保證。我們不保證服務的準確性、可靠性或可用性。',
        limitationOfLiability: '責任限制',
        limitationOfLiabilityContent: '在法律允許的最大範圍內，我們不對因使用服務而產生的任何間接、附帶、特殊、後果性或懲罰性損害負責。',
        termination: '終止',
        terminationContent: '我們可以立即終止或暫停您對服務的存取，無需事先通知，包括違反這些條款的情況。',
        governingLaw: '適用法律',
        governingLawContent: '這些條款應根據適用法律進行解釋和執行，不考慮法律衝突原則。',
        changes: '條款變更',
        changesContent: '我們保留隨時修改這些條款的權利。變更後繼續使用服務即表示接受新條款。',
        contact: '聯絡資訊',
        contactContent: '如果您對這些服務條款有任何疑問，請透過我們的聯絡頁面與我們聯繫。',
      },
      cookiePolicy: {
        title: 'Cookie政策',
        lastUpdated: '最後更新：2025年1月1日',
        introduction: '本Cookie政策說明殺手數獨分數在您造訪我們的網站時如何使用Cookie和類似技術。',
        whatAreCookies: '什麼是Cookie',
        whatAreCookiesContent: 'Cookie是當您造訪網站時儲存在您裝置上的小型文字檔案。它們幫助網站記住您造訪的相關資訊。',
        howWeUseCookies: '我們如何使用Cookie',
        howWeUseCookiesContent: '我們使用Cookie來：記住您的語言偏好、儲存遊戲進度、維持用戶會話，以及改善網站功能。',
        typesOfCookies: '我們使用的Cookie類型',
        essentialCookies: '必要Cookie',
        essentialCookiesContent: '這些Cookie是網站正常運作所必需的。它們啟用基本功能，如頁面導航和存取安全區域。',
        preferenceCookies: '偏好Cookie',
        preferenceCookiesContent: '這些Cookie記住您的選擇和偏好，如語言設定和主題選擇。',
        analyticsCookies: '分析Cookie',
        analyticsCookiesContent: '這些Cookie透過收集匿名資訊幫助我們了解訪客如何與我們的網站互動。',
        managingCookies: '管理Cookie',
        managingCookiesContent: '您可以透過瀏覽器設定控制Cookie。但是，停用Cookie可能會影響網站功能。',
        thirdPartyCookies: '第三方Cookie',
        thirdPartyCookiesContent: '我們可能使用設定自己Cookie的第三方服務。請查看他們的隱私政策以獲取更多資訊。',
        updates: '政策更新',
        updatesContent: '我們可能會不時更新此Cookie政策。請定期檢查此頁面以獲取任何變更。',
        contact: '聯絡我們',
        contactContent: '如果您對我們使用Cookie有任何疑問，請透過我們的聯絡頁面與我們聯繫。',
      },
      contact: {
        title: '聯絡我們',
        lastUpdated: '最後更新：2025年1月1日',
        introduction: '我們歡迎您對殺手數獨分數的意見回饋、問題和建議。',
        waysToContact: '聯絡我們的方式',
        email: '電子郵件',
        emailContent: '對於一般詢問、技術支援或意見回饋，請發送電子郵件給我們。',
        github: 'GitHub',
        githubContent: '對於技術問題、錯誤報告或功能請求，請造訪我們的GitHub儲存庫。',
        responseTime: '回應時間',
        responseTimeContent: '我們目標在營業日內48小時內回應所有詢問。',
        typesOfInquiries: '我們處理的詢問類型',
        technicalSupport: '技術支援',
        technicalSupportContent: '遊戲功能問題、瀏覽器相容性或效能問題。',
        privacyConcerns: '隱私疑慮',
        privacyConcernsContent: '關於資料收集、使用或隱私政策的問題。',
        featureRequests: '功能請求',
        featureRequestsContent: '新功能建議或現有功能的改進建議。',
        bugReports: '錯誤報告',
        bugReportsContent: '遊戲中錯誤、故障或意外行為的報告。',
        feedback: '一般意見回饋',
        feedbackContent: '對遊戲體驗的評論、建議或一般意見回饋。',
        beforeContacting: '聯絡我們之前',
        beforeContactingContent: '請查看我們的常見問題部分，並確保您使用的是最新版本的瀏覽器。許多問題可以透過清除瀏覽器快取或更新瀏覽器來解決。',
        privacyNote: '隱私注意事項',
        privacyNoteContent: '聯絡我們時，除非必要，請勿包含敏感的個人資訊除非必要。我們只會使用您的資訊來回應您的詢問。',
        businessHours: '營業時間',
        businessHoursContent: '我們通常在週一至週五上午9點至下午5點（UTC）回應詢問。',
      },
    },
  },
  ko: {
    // 遊戲相關
    gameTitle: '킬러 스도쿠',
    newGame: '새 게임',
    gameRules: '게임 규칙',
    difficulty: '난이도',
    easy: '쉬움',
    medium: '보통',
    hard: '어려움',
    expert: '전문가',
    hell: '지옥',

    // Theme & Language
    theme: '테마',
    mode: '모드',
    themeLight: '라이트',
    themeDark: '다크',
    language: '언어',
    login: '로그인',
    logout: '로그아웃',

    // 多巴胺 모드
    dopamineMode: '도파민 모드',
    startChallenge: '도전 시작',
    remaining: '남은',
    score: '점수',
    combo: 'COMBO',

    // 註解功能
    showNotes: '표시',
    hideNotes: '숨기기',
    notes: '메모',
    notesOn: '메모 ON',
    notesOff: '메모 OFF',
    notesModeOn: '메모 모드 활성화',
    notesModeOff: '메모 모드 비활성화',
    candidateNumbers: '후보 숫자',

    // Player Hub
    playerHub: '플레이어 허브',
    myStats: '내 통계',
    statsMode: '통계 모드',
    // Table Headers
    colDifficulty: '난이도',
    colGames: '횟수',
    colTime: '시간',
    colScore: '점수',
    colPlayer: '플레이어',
    top50: '상위 50위',

    pleaseRegister: '등록하고 플레이',
    userLimited: '유저 전용',

    // Dopamine Mode
    registerToUnlock: '등록하고 더 많은 기능 해제!',
    exclusiveFeature: '독점 기능',
    comboRewardSystem: '콤보 보상 시스템',
    hellDifficulty: '지옥 난이도',
    exclusiveLeaderboard: '전용 순위표',
    globalLeaderboardCompetition: '글로벌 순위 경쟁',
    competeWithGlobal: '전 세계 플레이어와 경쟁',
    rankByDifficulty: '난이도별 순위',
    personalBest: '개인 최고 기록',
    permanentRecord: '영구 게임 기록',
    howToRegister: '등록 유저가 되는 방법?',
    enterUsername: '사용자 이름 입력',
    chooseUniqueName: '고유한 사용자 이름 선택',
    startPlayingNow: '지금 게임 시작',
    noComplexVerification: '복잡한 인증 불필요',
    dataAutoSync: '데이터 자동 동기화',
    recordSavedToCloud: '게임 기록 클라우드 자동 저장',
    becomeRegisteredUser: '등록 유저 되기',
    continueAsGuest: '게스트로 계속하기',


    // 提示功能
    hint: '힌트',
    hintCountUsedUp: '힌트 횟수가 모두 사용되었습니다',

    // 遊戲控制
    clickToResume: '클릭하여 재개',
    clickToPause: '클릭하여 일시정지',
    dopamineModeVisitorOnly: '도파민 모드 - 등록된 사용자만',

    // 其他
    githubRepository: 'GitHub 저장소',

    // 도파민 정보 카드
    dopamineInfoTitle: '도파민 모드',
    dopamineInfoSubtitle: '한계에 도전하세요!',
    dopamineFeatures: '모드 특징',
    dopamineRules: '게임 규칙',
    basicAchievement: '기본 성취감',
    moderateChallenge: '적당한 도전',
    highAchievement: '높은 성취감',
    topChallenge: '최고 도전',
    highestAchievement: '최고 성취감',
    selectDifficulty: '난이도 선택',
    startDopamineChallenge: '도전 시작',
    challengeYourLimits: '한계에 도전',
    // userLimited: '사용자 제한', // This was a duplicate, removed as per instruction
    beyondNormalMode: '일반 모드 초월',
    modeFeatures: '모드 특징',
    selectChallengeDifficulty: '도전 난이도 선택',
    chooseDifficultyChallenge: '난이도 도전 선택, 특정 난이도에 집중',
    specialScoringSystem: '특별 점수 시스템, 콤보와 속도 보상',
    timeLimitChallenge: '시간 제한 내에 스도쿠 도전 완료',
    errorCountAffectsScore: '오류 횟수가 최종 점수에 영향',
    consecutiveCorrectReward: '연속 정확한 입력으로 콤보 보상 획득',
    speedCompletionBonus: '완료 속도가 빠를수록 높은 점수 보너스',
    challengeFailed: '도전 실패',
    dopamineAchievementWall: '도파민 성취 벽',
    noTopScoreData: '최고 점수 데이터 없음',
    difficultyLevel: '난이도 레벨',
    againChallenge: '다시 도전',
    returnToMainMenu: '메인 메뉴로 돌아가기',
    congratulationsComplete: '축하합니다 완료',
    successfullyCompletedGame: '게임을 성공적으로 완료했습니다',
    currentRank: '현재 순위',
    totalScore: '총 점수',
    newRecord: '새 기록!',
    completionTime: '완료 시간',
    errorCount: '오류 횟수',
    playAgain: '다시 플레이',
    viewLeaderboardButton: '리더보드 보기',
    congratulations: '축하합니다',
    remainingTime: '남은 시간',
    maxCombo: '최대 콤보',

    // 리더보드
    leaderboard: '리더보드',
    viewLeaderboard: '리더보드 보기',
    viewHighestScore: '최고 점수 보기',
    all: '전체',
    gamesPlayed: '게임',
    achievementWall: '성취 벽',
    noData: '데이터 없음',
    highestScoreDisplay: '최고 점수 표시',
    leaderboardPageTitle: '순위표',
    highestScoreTitle: '최고 점수',
    backToGame: '게임으로 돌아가기',

    // 사용자 관련
    welcome: '환영합니다',
    welcomeToKillerSudoku: '킬러 스도쿠에 오신 것을 환영합니다',
    enterNameToStart: '게임을 시작하고 리더보드에 참여하려면 이름을 입력하세요',
    welcomeUser: '환영합니다, ',

    // User Status
    userStatusTitle: '사용자 상태',
    userStatusDesc: '게임 데이터가 로컬에 저장됩니다',
    nameLabel: '이름',
    userIdLabel: '시스템 ID',
    joinDateLabel: '가입일',
    unknownDate: '알 수 없음',
    switchUser: '사용자 전환',

    enterYourName: '이름을 입력하세요',
    processing: '처리 중...',
    startGame: '게임 시작',
    visitorMode: '방문자 모드',
    visitorModeDescription: '방문자 모드는 점수가 기록되지 않으며 리더보드에 참여하지 않습니다',
    checkNetworkConnection: '네트워크 연결을 확인하거나 나중에 다시 시도해주세요. 문제가 지속되면 관리자에게 문의하세요.',
    viewStats: '통계 보기',
    normal: '일반',
    dopamine: '도파민',
    // pleaseRegister: '등록하고 플레이', // This was a duplicate, removed as per instruction

    // 일반
    close: '닫기',
    back: '뒤로',
    restart: '다시 도전',
    returnToMain: '메인 메뉴로',
    clear: '지우기',

    // 테마
    currentTheme: '현재 테마',
    clickToToggle: '라이트/다크 모드 전환',

    // 로딩 상태
    loadingStats: '통계 로딩 중...',

    // 사용자 통계
    bestScore: '최고 점수',
    bestTime: '최고 시간',
    totalGames: '총 게임 수',

    // 게임 규칙
    scoringSystem: '점수 시스템',
    rules: '규칙',
    scoring: '점수',
    tips: '해결 팁',
    basicRules: '기본 규칙',
    killerSudokuFeatures: '킬러 스도쿠 특징',
    solvingStrategy: '해결 전략',
    uniqueCandidate: '유일 후보수',
    hiddenSingle: '숨겨진 단수',
    killerSudokuTips: '킬러 스도쿠 팁',
    speedImprovement: '속도 향상',
    leaderboardDescription: '난이도별 순위표, 각 난이도의 최고 점수 표시',
    rankingCriteria: '순위 기준: 점수 → 최고 시간 → 게임 횟수',
    autoUpdate: '게임 완료 후 순위표 자동 업데이트',
    transparentScoring: '점수 계산 과정 완전 기록으로 공정성과 투명성 보장',
    basicScore: '기본 점수',
    timeBonus: '시간 보너스',
    mistakePenalty: '실수 페널티',
    calculationFormula: '계산 공식',
    finalScoreFormula: '최종 점수 = max(기본 점수 × 0.2, 기본 점수 + 시간 보너스 - 실수 페널티)',
    idealTime: '이상 시간',
    earlyBonus: '조기 완료',
    overtimePenalty: '시간 초과',
    mistake: '실수',
    mistakes: '실수',

    minimumScore: '최소 점수',
    example: '예시',
    points: '점',
    minutes: '분',
    basicRulesDescription: '9×9 격자에 1-9 숫자를 채우세요. 각 행, 열, 3×3 박스는 고유한 숫자를 포함해야 합니다.',
    killerSudokuFeaturesDescription: '점선 상자 안의 숫자는 왼쪽 상단 숫자의 합과 같아야 하며, 상자 내에서 반복될 수 없습니다.',
    solvingStrategyDescription: '가능한 숫자가 하나뿐인 셀부터 시작하여 다른 셀을 점진적으로 추론하세요.',
    uniqueCandidateDescription: '행, 열 또는 박스에서 숫자가 하나의 가능한 위치만 있다면 그것이 답입니다.',
    hiddenSingleDescription: '셀에 하나의 숫자만 넣을 수 있다면 그것이 답입니다.',
    killerSudokuTipsDescription: '점선 상자의 합 제약을 활용하여 불가능한 숫자 조합을 제거하세요.',
    speedImprovementDescription: '연습을 통해 여러 제약을 동시에 고려하여 해결 속도를 향상시키세요.',
    earlyBonusDescription: '1초당 +0.5점 조기 완료 (최대 500점)',
    overtimePenaltyDescription: '1초당 -0.1점 시간 초과 (최소 0점)',
    idealTimeDescription: '쉬움 6분, 보통 12분, 어려움 18분, 전문가 24분',
    mistakePenaltyDescription: '실수당 20점 차감',
    minimumScoreDescription: '기본 점수의 20%',
    minimumScoreExamples: '(쉬움 20점, 보통 40점, 어려움 60점, 전문가 100점)',
    scoringExample: '쉬움 모드, 2분 완료, 1회 실수 = 100 + 240 - 20 = 320점',

    // SEO 相關
    app_title: '킬러 스도쿠 - 무료 온라인 퍼즐 게임 | 킬러 스도쿠 퍼즐 게임',
    app_description: '무료 킬러 스도쿠 게임! 5가지 난이도, 도파민 모드, 글로벌 리더보드. 다운로드 없이 바로 플레이! 학생, 직장인, 시니어에게 완벽한 게임.',
    app_keywords: '킬러 스도쿠,스도쿠,퍼즐 게임,무료 게임,온라인 게임,스도쿠 게임,무료 퍼즐 게임,두뇌 게임,도파민 스도쿠,리더보드,한국어,스도쿠 챌린지,스도쿠 퍼즐,무료 퍼즐,두뇌 훈련',
    app_name: '킬러 스도쿠',
    game_category: '퍼즐 게임',
    game_genre: '스도쿠',
    game_platform: '웹 게임',
    audience_type: '학생, 직장인, 시니어',
    game_image_alt: '킬러 스도쿠 게임 스크린샷',
    og_locale: 'ko_KR',

    // Footer Legal Links
    footer: {
      about: '소개',
      howToPlay: '게임 방법',
      strategy: '전략',
      terms: '서비스 이용약관',
      privacy: '개인정보처리방침',
      cookies: '쿠키',
      contact: '문의하기',
    },

    // Content Pages
    about: {
      seoTitle: '킬러 스도쿠 소개 - 최고의 온라인 퍼즐 게임',
      seoDescription: '킬러 스도쿠에 대해 알아보고, 최고의 무료 온라인 퍼즐 경험을 제공하려는 우리의 사명과 매일의 두뇌 훈련을 위해 우리를 선택해야 하는 이유를 확인하세요.',
      title: '소개',
      backToGame: '게임으로 돌아가기',
      whatWeDo: {
        title: '우리가 하는 일',
        p1: '우리는 모든 레벨의 플레이어에게 최고의 온라인 킬러 스도쿠 경험을 제공하기 위해 최선을 다하고 있습니다. 우리의 플랫폼은 고전적인 스도쿠 규칙과 산술 도전을 결합하여 독특하고 매력적인 퍼즐 게임을 만듭니다.',
        p2: '기초를 배우려는 초보자이든 도전을 찾는 전문가이든, 우리 게임은 귀하의 필요에 맞는 다양한 난이도와 모드를 제공합니다.',
      },
      whyUs: {
        title: '우리를 선택해야 하는 이유',
        li1: '다운로드 없이 완전 무료 플레이',
        li2: '쉬움부터 지옥까지 다양한 난이도',
        li3: '빠른 속도의 재미를 위한 독특한 도파민 모드',
        li4: '전 세계 플레이어와 경쟁할 수 있는 글로벌 리더보드',
      },
      contact: {
        title: '문의하기',
        p1: '질문이나 의견이 있으신가요? 귀하의 의견을 듣고 싶습니다. 문의 페이지를 방문하여 연락해 주세요.',
      },
    },
    howToPlay: {
      seoTitle: '킬러 스도쿠 게임 방법 - 규칙 및 팁',
      seoDescription: '포괄적인 가이드를 통해 킬러 스도쿠 규칙을 마스터하세요. 기본 규칙, 점수 시스템 및 퍼즐을 더 빨리 푸는 팁을 배우세요.',
      title: '게임 방법',
      backToGame: '게임으로 돌아가기',
      rules: {
        title: '게임 규칙',
        li1: '9x9 격자에 1-9 숫자를 채워 각 행, 열, 3x3 박스에 모든 숫자가 정확히 한 번씩 포함되도록 합니다.',
        li2: '격자는 점선 상자로 나뉩니다. 상자 안의 숫자 합은 왼쪽 상단의 작은 숫자와 같아야 합니다.',
        li3: '상자 내에서 숫자는 반복될 수 없습니다.',
      },
      tips: {
        title: '성공을 위한 팁',
        li1: '가능한 조합이 하나뿐인 상자부터 시작하세요 (예: 합이 3인 2칸 상자는 1과 2여야 함).',
        li2: '45 규칙 사용: 모든 행, 열 또는 3x3 박스의 숫자 합은 항상 45입니다.',
        li3: '상자 합과 45 규칙을 비교하여 "내부 수"와 "외부 수"를 찾으세요.',
      },
      scoring: {
        title: '점수 시스템',
        p1: '점수는 난이도, 완료 시간 및 실수를 기준으로 계산됩니다. 도파민 모드에서는 속도와 콤보에 대한 보너스도 받습니다!',
      },
    },
    strategy: {
      seoTitle: '킬러 스도쿠 공략 - 고급 기술',
      seoDescription: '공략 가이드를 통해 킬러 스도쿠 실력을 향상시키세요. 고급 기술, 피해야 할 일반적인 실수 및 전문가 퍼즐을 푸는 방법을 배우세요.',
      title: '공략 가이드',
      backToGame: '게임으로 돌아가기',
      common: {
        title: '일반적인 전략',
        li1: '유일한 합 찾기: 일부 상자 합은 숫자의 가능한 조합이 하나뿐입니다.',
        li2: '45 규칙: 모든 행, 열, 박스의 합이 45라는 사실을 이용하여 경계를 넘는 상자의 숫자를 추론하세요.',
        li3: '상자 조합: 해결 속도를 높이기 위해 2, 3, 4칸의 일반적인 합을 외우세요.',
        li4: '연필 표시: 메모를 사용하여 각 셀의 가능한 후보를 추적하세요.',
      },
      advanced: {
        title: '고급 전술',
        li1: '내부 수와 외부 수: 상자 합과 45의 차이를 계산하여 영역 내부 또는 외부의 숫자를 찾으세요.',
        li2: '상자 분할: 복잡한 상자를 더 작고 관리하기 쉬운 부분으로 나누세요.',
        li3: '홀짝 분석: 때로는 숫자가 홀수인지 짝수인지 아는 것이 가능성을 제거하는 데 도움이 될 수 있습니다.',
      },
      mistakes: {
        title: '일반적인 실수',
        li1: '추측: 절대 추측하지 마세요. 항상 논리를 사용하여 다음 숫자를 추론하세요.',
        li2: '제약 무시: 상자 합 외에도 행, 열, 박스 제약을 확인하는 것을 잊지 마세요.',
        li3: '서두름: 특히 높은 난이도에서는 보드를 분석하는 데 시간을 투자하세요.',
      },
    },

    // 법적 문서
    legal: {
      privacyPolicy: {
        title: '개인정보처리방침',
        lastUpdated: '최종 업데이트: 2025년 1월 1일',
        introduction: '본 개인정보처리방침은 킬러 스도쿠 스코어("우리", "저희", "회사")가 웹 애플리케이션을 사용할 때 귀하의 정보를 수집, 사용 및 보호하는 방법을 설명합니다.',
        informationCollection: '수집하는 정보',
        informationCollectionContent: '저희는 서비스 제공에 필요한 최소한의 정보만 수집합니다: 사용자명(리더보드 참여용), 게임 통계(점수, 완료 시간), 기술 데이터(브라우저 유형, 기기 정보).',
        informationUse: '정보 사용 방법',
        informationUseContent: '귀하의 정보는 다음 목적으로만 사용됩니다: 게임 기능 제공, 리더보드 유지, 사용자 경험 개선, 서비스 보안 확보. 저희는 귀하의 개인 데이터를 제3자에게 판매하거나 공유하지 않습니다.',
        dataStorage: '데이터 저장 및 보안',
        dataStorageContent: '귀하의 데이터는 업계 표준 암호화를 사용하여 안전하게 저장됩니다. 저희는 무단 접근, 변경, 공개 또는 파괴로부터 보호하기 위한 적절한 기술적 및 조직적 조치를 구현합니다.',
        cookies: '쿠키 및 로컬 저장소',
        cookiesContent: '저희는 쿠키와 로컬 저장소를 사용하여 귀하의 환경설정, 게임 진행 상황 및 언어 설정을 기억합니다. 브라우저 설정에서 쿠키를 비활성화할 수 있지만, 이는 기능에 영향을 줄 수 있습니다.',
        userRights: '귀하의 권리',
        userRightsContent: '귀하는 개인 데이터에 접근, 업데이트 또는 삭제할 권리가 있습니다. 이러한 권리를 행사하려면 저희에게 연락하세요. 방문자 모드를 사용하여 리더보드 참여를 거부할 수도 있습니다.',
        changes: '정책 변경',
        changesContent: '저희는 이 개인정보처리방침을 주기적으로 업데이트할 수 있습니다. 중요한 변경사항이 있을 경우 애플리케이션이나 웹사이트를 통해 사용자에게 알려드립니다.',
        contact: '연락처 정보',
        contactContent: '이 개인정보처리방침에 대한 질문이 있으시면 연락처 페이지를 통해 저희에게 연락하세요.',
      },
      termsOfService: {
        title: '서비스 이용약관',
        lastUpdated: '최종 업데이트: 2025년 1월 1일',
        acceptance: '약관 수락',
        acceptanceContent: '킬러 스도쿠 스코어에 접근하고 사용함으로써 귀하는 이 계약의 약관 및 조항에 구속되는 것에 동의합니다.',
        serviceDescription: '서비스 설명',
        serviceDescriptionContent: '킬러 스도쿠 스코어는 점수 시스템과 리더보드가 있는 스도쿠 도전을 제공하는 웹 기반 퍼즐 게임입니다. 서비스는 보증 없이 "있는 그대로" 제공됩니다.',
        userConduct: '사용자 행동',
        userConductContent: '사용자는 다음에 동의합니다: 서비스를 합법적으로 사용하고, 점수나 순위를 조작하려고 시도하지 않으며, 다른 사용자를 존중하고, 해로운 또는 방해가 되는 행동에 관여하지 않습니다.',
        intellectualProperty: '지적재산권',
        intellectualPropertyContent: '게임 로직, 디자인 및 코드를 포함한 모든 콘텐츠는 지적재산권 법률에 의해 보호됩니다. 사용자는 허가 없이 저희 콘텐츠를 복사, 수정 또는 배포할 수 없습니다.',
        privacy: '개인정보보호',
        privacyContent: '귀하의 개인정보보호는 저희에게 중요합니다. 저희가 귀하의 정보를 수집하고 사용하는 방법을 이해하려면 개인정보처리방침을 검토해 주세요.',
        serviceAvailability: '서비스 가용성',
        serviceAvailabilityContent: '저희는 서비스 가용성을 유지하기 위해 노력하지만 중단 없는 접근을 보장할 수는 없습니다. 저희는 언제든지 서비스를 수정하거나 중단할 권리를 보유합니다.',
        disclaimer: '면책 조항',
        disclaimerContent: '서비스는 어떠한 종류의 보증 없이 "있는 그대로" 제공됩니다. 저희는 서비스의 정확성, 신뢰성 또는 가용성을 보장하지 않습니다.',
        limitationOfLiability: '책임 제한',
        limitationOfLiabilityContent: '법률이 허용하는 최대 범위 내에서 저희는 서비스 사용으로 인해 발생하는 간접적, 부수적, 특별, 결과적 또는 징벌적 손해에 대해 책임지지 않습니다.',
        termination: '계약 해지',
        terminationContent: '저희는 이러한 약관 위반을 포함하여 어떤 이유로든 사전 통지 없이 귀하의 서비스 접근을 즉시 종료하거나 중단할 수 있습니다.',
        governingLaw: '준거법',
        governingLawContent: '이 약관은 법률 충돌 원칙을 고려하지 않고 적용 가능한 법률에 따라 해석되고 적용됩니다.',
        changes: '약관 변경',
        changesContent: '저희는 언제든지 이 약관을 수정할 권리를 보유합니다. 변경 후 서비스를 계속 사용하는 것은 새로운 약관에 대한 수락을 의미합니다.',
        contact: '연락처 정보',
        contactContent: '이 서비스 이용약관에 대한 질문이 있으시면 연락처 페이지를 통해 저희에게 연락하세요.',
      },
      cookiePolicy: {
        title: '쿠키 정책',
        lastUpdated: '최종 업데이트: 2025년 1월 1일',
        introduction: '본 쿠키 정책은 킬러 스도쿠 스코어가 귀하가 저희 웹사이트를 방문할 때 쿠키와 유사한 기술을 사용하는 방법을 설명합니다.',
        whatAreCookies: '쿠키란 무엇인가',
        whatAreCookiesContent: '쿠키는 웹사이트를 방문할 때 기기에 저장되는 작은 텍스트 파일입니다. 웹사이트가 방문에 대한 정보를 기억하는 데 도움이 됩니다.',
        howWeUseCookies: '쿠키 사용 방법',
        howWeUseCookiesContent: '저희는 쿠키를 사용하여: 언어 환경설정을 기억하고, 게임 진행 상황을 저장하며, 사용자 세션을 유지하고, 웹사이트 기능을 개선합니다.',
        typesOfCookies: '사용하는 쿠키 유형',
        essentialCookies: '필수 쿠키',
        essentialCookiesContent: '이러한 쿠키는 웹사이트가 제대로 작동하는 데 필요합니다. 페이지 탐색 및 보안 영역 접근과 같은 기본 기능을 활성화합니다.',
        preferenceCookies: '환경설정 쿠키',
        preferenceCookiesContent: '이러한 쿠키는 언어 설정 및 테마 선택과 같은 귀하의 선택과 환경설정을 기억합니다.',
        analyticsCookies: '분석 쿠키',
        analyticsCookiesContent: '이러한 쿠키는 익명 정보를 수집하여 방문자가 저희 웹사이트와 어떻게 상호작용하는지 이해하는 데 도움이 됩니다.',
        managingCookies: '쿠키 관리',
        managingCookiesContent: '브라우저 설정을 통해 쿠키를 제어할 수 있습니다. 그러나 쿠키를 비활성화하면 웹사이트 기능에 영향을 줄 수 있습니다.',
        thirdPartyCookies: '제3자 쿠키',
        thirdPartyCookiesContent: '저희는 자체 쿠키를 설정하는 제3자 서비스를 사용할 수 있습니다. 더 많은 정보는 해당 서비스의 개인정보처리방침을 검토해 주세요.',
        updates: '정책 업데이트',
        updatesContent: '저희는 이 쿠키 정책을 수시로 업데이트할 수 있습니다. 변경사항을 확인하려면 이 페이지를 정기적으로 확인해 주세요.',
        contact: '문의하기',
        contactContent: '쿠키 사용에 대한 질문이 있으시면 연락처 페이지를 통해 저희에게 연락하세요.',
      },
      contact: {
        title: '문의하기',
        lastUpdated: '최종 업데이트: 2025년 1월 1일',
        introduction: '저희는 킬러 스도쿠 스코어에 대한 귀하의 피드백, 질문 및 제안을 환영합니다.',
        waysToContact: '연락 방법',
        email: '이메일',
        emailContent: '일반 문의, 기술 지원 또는 피드백의 경우 이메일을 보내주세요.',
        github: 'GitHub',
        githubContent: '기술적 문제, 버그 리포트 또는 기능 요청의 경우 저희 GitHub 저장소를 방문해 주세요.',
        responseTime: '응답 시간',
        responseTimeContent: '저희는 영업일 기준 48시간 내에 모든 문의에 응답하는 것을 목표로 합니다.',
        typesOfInquiries: '처리하는 문의 유형',
        technicalSupport: '기술 지원',
        technicalSupportContent: '게임 기능 문제, 브라우저 호환성 또는 성능 문제.',
        privacyConcerns: '개인정보보호 우려',
        privacyConcernsContent: '데이터 수집, 사용 또는 개인정보처리방침에 대한 질문.',
        featureRequests: '기능 요청',
        featureRequestsContent: '새로운 기능이나 기존 기능 개선에 대한 제안.',
        bugReports: '버그 리포트',
        bugReportsContent: '게임의 오류, 결함 또는 예상치 못한 동작에 대한 보고.',
        feedback: '일반 피드백',
        feedbackContent: '게임 경험에 대한 의견, 제안 또는 일반적인 피드백.',
        beforeContacting: '문의하기 전에',
        beforeContactingContent: 'FAQ 섹션을 확인하고 최신 버전의 브라우저를 사용하고 있는지 확인해 주세요. 많은 문제는 브라우저 캐시를 지우거나 브라우저를 업데이트하여 해결할 수 있습니다.',
        privacyNote: '개인정보보호 참고사항',
        privacyNoteContent: '문의할 때는 필요하지 않은 한 민감한 개인 정보를 포함하지 마세요. 저희는 귀하의 정보를 문의에 응답하는 목적으로만 사용합니다.',
        businessHours: '영업 시간',
        businessHoursContent: '저희는 일반적으로 월요일부터 금요일까지 오전 9시부터 오후 5시(UTC)까지 문의에 응답합니다.',
      },
    },
  },
  ja: {
    // ゲーム関連
    gameTitle: 'キラー数独',
    newGame: '新しいゲーム',
    gameRules: 'ゲームルール',
    difficulty: '難易度',
    easy: '初級',
    medium: '中級',
    hard: '上級',
    expert: '達人',
    hell: '地獄級',

    // Theme & Language
    theme: 'テーマ',
    themeLight: 'ライト',
    themeDark: 'ダーク',
    language: '言語',
    mode: 'モード',
    login: 'ログイン',
    logout: 'ログアウト',

    // ドーパミンモード
    dopamineMode: 'ドーパミンモード',
    startChallenge: 'チャレンジ開始',
    remaining: '残り',
    score: 'スコア',
    combo: 'COMBO',

    // 註解功能
    showNotes: '表示',
    hideNotes: '非表示',
    notes: 'メモ',
    notesOn: 'メモON',
    notesOff: 'メモOFF',
    notesModeOn: 'メモモード有効',
    notesModeOff: 'メモモード無効',
    candidateNumbers: '候補数字',

    // 提示功能
    hint: 'ヒント',
    hintCountUsedUp: 'ヒント回数が使い切れました',

    // 遊戲控制
    clickToResume: 'クリックして再開',
    clickToPause: 'クリックして一時停止',
    dopamineModeVisitorOnly: 'ドーパミンモード - 登録ユーザーのみ',

    // 其他
    githubRepository: 'GitHub リポジトリ',

    // ドーパミン情報カード
    dopamineInfoTitle: 'ドーパミンモード',
    dopamineInfoSubtitle: '限界に挑戦しよう！',
    dopamineFeatures: 'モード特徴',
    dopamineRules: 'ゲームルール',
    basicAchievement: '基本達成感',
    moderateChallenge: '適度な挑戦',
    highAchievement: '高い達成感',
    topChallenge: '最高挑戦',
    highestAchievement: '最高達成感',
    selectDifficulty: '難易度選択',
    startDopamineChallenge: 'チャレンジ開始',
    challengeYourLimits: '限界に挑戦',
    // userLimited: 'ユーザー限定', // This was a duplicate, removed as per instruction
    beyondNormalMode: '通常モードを超越',
    modeFeatures: 'モード特徴',
    selectChallengeDifficulty: 'チャレンジ難易度選択',
    chooseDifficultyChallenge: '難易度チャレンジ選択、特定の難易度に集中',
    specialScoringSystem: '特別スコアシステム、コンボとスピード報酬',
    timeLimitChallenge: '時間制限内に数独チャレンジ完了',
    errorCountAffectsScore: 'エラー回数が最終スコアに影響',
    consecutiveCorrectReward: '連続正解入力でコンボ報酬獲得',
    speedCompletionBonus: '完了速度が速いほど高いスコアボーナス',
    challengeFailed: 'チャレンジ失敗',
    dopamineAchievementWall: 'ドーパミン実績ウォール',
    noTopScoreData: '最高スコアデータなし',
    difficultyLevel: '難易度レベル',
    againChallenge: '再チャレンジ',
    returnToMainMenu: 'メインメニューに戻る',
    congratulationsComplete: 'おめでとうございます 完了',
    successfullyCompletedGame: 'ゲームを正常に完了しました',
    currentRank: '現在のランク',
    totalScore: '総スコア',
    newRecord: '新記録！',
    completionTime: '完了時間',
    errorCount: 'エラー回数',
    playAgain: 'もう一度プレイ',
    viewLeaderboardButton: 'リーダーボードを見る',
    congratulations: 'おめでとうございます',
    remainingTime: '残り時間',
    maxCombo: '最大コンボ',

    // リーダーボード
    leaderboard: 'リーダーボード',
    viewLeaderboard: 'リーダーボードを見る',
    viewHighestScore: '最高スコアを見る',
    all: '全て',
    gamesPlayed: 'ゲーム',
    achievementWall: '実績ウォール',
    noData: 'データなし',
    highestScoreDisplay: 'ハイスコア表示',
    leaderboardPageTitle: 'リーダーボード',
    highestScoreTitle: 'ハイスコア',
    backToGame: 'ゲームに戻る',

    // ユーザー関連
    welcome: 'ようこそ',
    welcomeToKillerSudoku: 'キラー数独へようこそ',
    enterNameToStart: 'ゲームを開始し、リーダーボードに参加するために名前を入力してください',
    welcomeUser: 'ようこそ、',

    // User Status
    userStatusTitle: 'ユーザーステータス',
    userStatusDesc: 'ゲームデータはローカルに保存されます',
    nameLabel: '名前',
    userIdLabel: 'ユーザーID',
    joinDateLabel: '参加日',
    unknownDate: '不明',
    switchUser: 'ユーザー切替',

    enterYourName: '名前を入力してください',
    processing: '処理中...',
    startGame: 'ゲーム開始',
    visitorMode: 'ゲストモード',
    visitorModeDescription: 'ゲストモードはスコアが記録されず、リーダーボードに参加しません',
    checkNetworkConnection: 'ネットワーク接続を確認するか、後でもう一度お試しください。問題が続く場合は、管理者にお問い合わせください。',
    viewStats: '統計を見る',
    normal: '通常',
    dopamine: 'ドーパミン',
    playerHub: 'プレイヤーセンター',
    myStats: '個人戦績',
    statsMode: '統計モード',
    // Table Headers
    colDifficulty: '難易度',
    colGames: '回数',
    colTime: '時間',
    colScore: 'スコア',
    colPlayer: 'プレイヤー',
    top50: 'トップ50',
    total: '合計',
    pleaseRegister: '登録してプレイ',
    userLimited: 'ユーザー限定',

    // Dopamine Mode
    registerToUnlock: '登録して機能を解除！',
    exclusiveFeature: '専用機能',
    comboRewardSystem: 'コンボ報酬システム',
    hellDifficulty: '地獄級難易度',
    exclusiveLeaderboard: '専用ランキング',
    globalLeaderboardCompetition: '世界ランキング競争',
    competeWithGlobal: '世界中のプレイヤーと競争',
    rankByDifficulty: '難易度別ランク',
    personalBest: '自己ベスト',
    permanentRecord: '永久ゲーム記録',
    howToRegister: '登録ユーザーになるには？',
    enterUsername: 'ユーザー名を入力',
    chooseUniqueName: 'ユニークな名前を選択',
    startPlayingNow: '今すぐプレイ',
    noComplexVerification: '複雑な認証は不要',
    dataAutoSync: 'データ自動同期',
    recordSavedToCloud: 'ゲーム記録をクラウドに自動保存',
    becomeRegisteredUser: '登録ユーザーになる',
    continueAsGuest: 'ゲストとして続ける',


    // 一般
    close: '閉じる',
    back: '戻る',
    restart: '再挑戦',
    returnToMain: 'メインメニューに戻る',
    clear: 'クリア',

    // テーマ
    currentTheme: '現在のテーマ',
    clickToToggle: 'ライト/ダークモード切り替え',

    // ローディング状態
    loadingStats: '統計読み込み中...',

    // ユーザー統計
    bestScore: '最高スコア',
    bestTime: '最高時間',
    totalGames: '総ゲーム数',

    // ゲームルール
    scoringSystem: 'スコアシステム',
    rules: 'ルール',
    scoring: 'スコア',
    tips: '解法のコツ',
    basicRules: '基本ルール',
    killerSudokuFeatures: 'キラー数独の特徴',
    solvingStrategy: '解法戦略',
    uniqueCandidate: '唯一候補数',
    hiddenSingle: '隠れた単数',
    killerSudokuTips: 'キラー数独のコツ',
    speedImprovement: '速度向上',
    leaderboardDescription: '難易度別ランキング、各難易度の最高スコア表示',
    rankingCriteria: 'ランキング基準：スコア → 最高時間 → ゲーム回数',
    autoUpdate: 'ゲーム完了後ランキング自動更新',
    transparentScoring: 'スコア計算過程完全記録で公平性と透明性を保証',
    basicScore: '基本スコア',
    timeBonus: '時間ボーナス',
    mistakePenalty: 'ミスペナルティ',
    calculationFormula: '計算式',
    finalScoreFormula: '最終スコア = max(基本スコア × 0.2, 基本スコア + 時間ボーナス - ミスペナルティ)',
    idealTime: '理想時間',
    earlyBonus: '早期完了',
    overtimePenalty: '時間超過',
    mistake: 'ミス',
    minimumScore: '最低スコア',
    example: '例',
    points: '点',
    minutes: '分',
    basicRulesDescription: '9×9のグリッドに1-9の数字を埋めてください。各行、列、3×3ボックスは一意の数字を含む必要があります。',
    killerSudokuFeaturesDescription: '破線ボックス内の数字は左上の数字の合計と等しく、ボックス内で重複してはいけません。',
    solvingStrategyDescription: '可能な数字が1つしかないセルから始めて、他のセルを段階的に推論してください。',
    uniqueCandidateDescription: '行、列、またはボックスで数字が1つの可能な位置しかない場合、それが答えです。',
    hiddenSingleDescription: 'セルに1つの数字しか入れられない場合、それが答えです。',
    killerSudokuTipsDescription: '破線ボックスの合計制約を活用して、不可能な数字の組み合わせを排除してください。',
    speedImprovementDescription: '練習により複数の制約を同時に考慮して、解決速度を向上させてください。',
    earlyBonusDescription: '1秒あたり+0.5点早期完了（最大500点）',
    overtimePenaltyDescription: '1秒あたり-0.1点時間超過（最小0点）',
    idealTimeDescription: '簡単6分、普通12分、困難18分、専門家24分',
    mistakePenaltyDescription: 'ミス1回につき20点減点',
    minimumScoreDescription: '基本スコアの20%',
    minimumScoreExamples: '（簡単20点、普通40点、困難60点、専門家100点）',
    scoringExample: '簡単モード、2分完了、1回ミス = 100 + 240 - 20 = 320点',

    // SEO 相關
    app_title: 'キラー数独 - 無料オンラインパズルゲーム | キラー数独パズルゲーム',
    app_description: '無料キラー数独ゲーム！5つの難易度、ドーパミンモード、グローバルリーダーボード。ダウンロード不要で今すぐプレイ！学生、会社員、シニアに最適。',
    app_keywords: 'キラー数独,数独,パズルゲーム,無料ゲーム,オンラインゲーム,数独ゲーム,無料パズルゲーム,脳トレゲーム,ドーパミン数独,リーダーボード,日本語,数独チャレンジ,数独パズル,無料パズル,脳力トレーニング',
    app_name: 'キラー数独',
    game_category: 'パズルゲーム',
    game_genre: '数独',
    game_platform: 'ウェブゲーム',
    audience_type: '学生、会社員、シニア',
    game_image_alt: 'キラー数独ゲームスクリーンショット',
    og_locale: 'ja_JP',

    // Footer Legal Links
    footer: {
      about: '運営者情報',
      howToPlay: '遊び方',
      strategy: '攻略法',
      terms: '利用規約',
      privacy: 'プライバシー',
      cookies: 'Cookie',
      contact: 'お問い合わせ',
    },

    // Content Pages
    about: {
      seoTitle: 'キラー数独について - 最高のオンラインパズルゲーム',
      seoDescription: 'キラー数独について、最高の無料オンラインパズル体験を提供するという私たちの使命、そして毎日の脳トレに私たちが選ばれる理由をご覧ください。',
      title: '運営者情報',
      backToGame: 'ゲームに戻る',
      whatWeDo: {
        title: '私たちの活動',
        p1: '私たちは、あらゆるレベルのプレイヤーに最高のオンラインキラー数独体験を提供することに専念しています。私たちのプラットフォームは、古典的な数独のルールと計算の課題を組み合わせて、ユニークで魅力的なパズルゲームを作成しています。',
        p2: '基本を学びたい初心者でも、挑戦を求める上級者でも、私たちのゲームはあなたのニーズに合った様々な難易度とモードを提供します。',
      },
      whyUs: {
        title: '選ばれる理由',
        li1: 'ダウンロード不要で完全無料プレイ',
        li2: '初級から地獄級まで多彩な難易度',
        li3: 'スピーディーな楽しさのためのユニークなドーパミンモード',
        li4: '世界中のプレイヤーと競えるグローバルリーダーボード',
      },
      contact: {
        title: 'お問い合わせ',
        p1: 'ご質問やご意見はありますか？お問い合わせページからお気軽にご連絡ください。',
      },
    },
    howToPlay: {
      seoTitle: 'キラー数独の遊び方 - ルールとヒント',
      seoDescription: '包括的なガイドでキラー数独のルールをマスターしましょう。基本ルール、スコアシステム、パズルをより速く解くためのヒントを学びます。',
      title: '遊び方',
      backToGame: 'ゲームに戻る',
      rules: {
        title: 'ゲームルール',
        li1: '9x9のグリッドに1から9の数字を入れ、各行、列、3x3ボックスにすべての数字が重複なく1回だけ含まれるようにします。',
        li2: 'グリッドは点線の枠（ケージ）で区切られています。ケージ内の数字の合計は、左上の小さな数字と等しくなければなりません。',
        li3: 'ケージ内で数字は重複できません。',
      },
      tips: {
        title: '成功のヒント',
        li1: '可能な組み合わせが1つしかないケージから始めましょう（例：合計が3の2マスは1と2でなければなりません）。',
        li2: '45の法則を使用：任意の行、列、または3x3ボックスの数字の合計は常に45です。',
        li3: 'ケージの合計と45の法則を比較して、「内側の数」と「外側の数」を探します。',
      },
      scoring: {
        title: 'スコアシステム',
        p1: 'スコアは難易度、完了時間、ミスに基づいて計算されます。ドーパミンモードでは、スピードとコンボのボーナスも獲得できます！',
      },
    },
    strategy: {
      seoTitle: 'キラー数独攻略 - 高度なテクニック',
      seoDescription: '攻略ガイドでキラー数独のスキルを向上させましょう。高度なテクニック、避けるべき一般的な間違い、達人レベルのパズルの解き方を学びます。',
      title: '攻略ガイド',
      backToGame: 'ゲームに戻る',
      common: {
        title: '一般的な戦略',
        li1: '一意の合計を探す：一部のケージの合計には、数字の可能な組み合わせが1つしかありません。',
        li2: '45の法則：すべての行、列、ボックスの合計が45であるという事実を利用して、境界を越えるケージ内の数字を推論します。',
        li3: 'ケージの組み合わせ：解決速度を上げるために、2、3、または4マスの一般的な合計を暗記します。',
        li4: '鉛筆マーク：メモを使用して、各セルの可能な候補を追跡します。',
      },
      advanced: {
        title: '高度な戦術',
        li1: '内側の数と外側の数：ケージの合計と45の差を計算して、領域の内側または外側の数字を見つけます。',
        li2: 'ケージの分割：複雑なケージをより小さく、管理しやすい部分に分解します。',
        li3: '偶奇分析：数字が奇数か偶数かを知ることで、可能性を排除できる場合があります。',
      },
      mistakes: {
        title: 'よくある間違い',
        li1: '推測：決して推測しないでください。常に論理を使用して次の数字を導き出してください。',
        li2: '制約の無視：ケージの合計に加えて、行、列、ボックスの制約を確認することを忘れないでください。',
        li3: '急ぐこと：特に高難易度では、ボードを分析するために時間をかけてください。',
      },
    },

    // 法的文書
    legal: {
      privacyPolicy: {
        title: 'プライバシーポリシー',
        lastUpdated: '最終更新：2025年1月1日',
        introduction: 'このプライバシーポリシーは、キラー数独スコア（「当社」、「私たち」）がウェブアプリケーションをご利用いただく際に、お客様の情報をどのように収集、使用、保護するかを説明します。',
        informationCollection: '収集する情報',
        informationCollectionContent: '当社は、サービス提供に必要な最小限の情報のみを収集します：ユーザー名（リーダーボード参加用）、ゲーム統計（スコア、完了時間）、技術データ（ブラウザタイプ、デバイス情報）。',
        informationUse: '情報の使用方法',
        informationUseContent: 'お客様の情報は以下の目的でのみ使用されます：ゲーム機能の提供、リーダーボードの維持、ユーザー体験の向上、サービスセキュリティの確保。当社はお客様の個人データを第三者に販売または共有することはありません。',
        dataStorage: 'データ保存とセキュリティ',
        dataStorageContent: 'お客様のデータは業界標準の暗号化を使用して安全に保存されます。当社は、不正アクセス、変更、開示、または破壊から保護するための適切な技術的および組織的措置を実装しています。',
        cookies: 'Cookieとローカルストレージ',
        cookiesContent: '当社はCookieとローカルストレージを使用して、お客様の設定、ゲーム進行状況、言語設定を記憶します。ブラウザ設定でCookieを無効にすることができますが、これにより機能に影響する場合があります。',
        userRights: 'お客様の権利',
        userRightsContent: 'お客様には個人データへのアクセス、更新、削除する権利があります。これらの権利を行使するには、当社にお問い合わせください。ゲストモードを使用してリーダーボード参加を拒否することもできます。',
        changes: 'ポリシーの変更',
        changesContent: '当社はこのプライバシーポリシーを定期的に更新する場合があります。重要な変更については、アプリケーションまたはウェブサイトを通じてユーザーに通知します。',
        contact: 'お問い合わせ情報',
        contactContent: 'このプライバシーポリシーについてご質問がございましたら、お問い合わせページから当社までご連絡ください。',
      },
      termsOfService: {
        title: '利用規約',
        lastUpdated: '最終更新：2025年1月1日',
        acceptance: '規約の承諾',
        acceptanceContent: 'キラー数独スコアにアクセスし使用することにより、お客様はこの契約の条項および規定に拘束されることに同意します。',
        serviceDescription: 'サービス説明',
        serviceDescriptionContent: 'キラー数独スコアは、スコアシステムとリーダーボードを備えた数独チャレンジを提供するウェブベースのパズルゲームです。サービスは保証なしで「現状のまま」提供されます。',
        userConduct: 'ユーザーの行動',
        userConductContent: 'ユーザーは以下に同意します：サービスを合法的に使用し、スコアやランキングを操作しようとせず、他のユーザーを尊重し、有害または破壊的な行動に従事しないこと。',
        intellectualProperty: '知的財産権',
        intellectualPropertyContent: 'ゲームロジック、デザイン、コードを含むすべてのコンテンツは、知的財産権法によって保護されています。ユーザーは許可なく当社のコンテンツを複製、変更、または配布することはできません。',
        privacy: 'プライバシー',
        privacyContent: 'お客様のプライバシーは当社にとって重要です。当社がお客様の情報をどのように収集し使用するかを理解するために、プライバシーポリシーをご確認ください。',
        serviceAvailability: 'サービスの可用性',
        serviceAvailabilityContent: '当社はサービスの可用性を維持するよう努めますが、中断のないアクセスを保証することはできません。当社はいつでもサービスを変更または中止する権利を留保します。',
        disclaimer: '免責事項',
        disclaimerContent: 'サービスはいかなる種類の保証もなく「現状のまま」提供されます。当社はサービスの正確性、信頼性、または可用性を保証しません。',
        limitationOfLiability: '責任の制限',
        limitationOfLiabilityContent: '法律で許可される最大限の範囲で、当社はサービスの使用から生じる間接的、付随的、特別、結果的、または懲罰的損害について責任を負いません。',
        termination: '契約終了',
        terminationContent: '当社は、これらの規約の違反を含む、いかなる理由でも事前通知なしに、お客様のサービスアクセスを即座に終了または停止することができます。',
        governingLaw: '準拠法',
        governingLawContent: 'これらの規約は、法の抵触原則を考慮せずに、適用される法律に従って解釈され適用されます。',
        changes: '規約の変更',
        changesContent: '当社はいつでもこれらの規約を変更する権利を留保します。変更後のサービスの継続使用は、新しい規約の受諾を意味します。',
        contact: 'お問い合わせ情報',
        contactContent: 'この利用規約についてご質問がございましたら、お問い合わせページから当社までご連絡ください。',
      },
      cookiePolicy: {
        title: 'Cookieポリシー',
        lastUpdated: '最終更新：2025年1月1日',
        introduction: 'このCookieポリシーは、キラー数独スコアがお客様が当社のウェブサイトを訪問する際にCookieと類似の技術をどのように使用するかを説明します。',
        whatAreCookies: 'Cookieとは',
        whatAreCookiesContent: 'Cookieは、ウェブサイトを訪問する際にデバイスに保存される小さなテキストファイルです。ウェブサイトが訪問に関する情報を記憶するのに役立ちます。',
        howWeUseCookies: 'Cookieの使用方法',
        howWeUseCookiesContent: '当社はCookieを使用して：言語設定を記憶し、ゲーム進行状況を保存し、ユーザーセッションを維持し、ウェブサイト機能を向上させます。',
        typesOfCookies: '使用するCookieの種類',
        essentialCookies: '必須Cookie',
        essentialCookiesContent: 'これらのCookieは、ウェブサイトが適切に機能するために必要です。ページナビゲーションやセキュアエリアへのアクセスなどの基本機能を有効にします。',
        preferenceCookies: '設定Cookie',
        preferenceCookiesContent: 'これらのCookieは、言語設定やテーマ選択など、お客様の選択と設定を記憶します。',
        analyticsCookies: '分析Cookie',
        analyticsCookiesContent: 'これらのCookieは、匿名情報を収集することで、訪問者が当社のウェブサイトとどのように相互作用するかを理解するのに役立ちます。',
        managingCookies: 'Cookieの管理',
        managingCookiesContent: 'ブラウザ設定を通じてCookieを制御できます。ただし、Cookieを無効にすると、ウェブサイトの機能に影響する場合があります。',
        thirdPartyCookies: '第三者Cookie',
        thirdPartyCookiesContent: '当社は独自のCookieを設定する第三者サービスを使用する場合があります。詳細については、それらのプライバシーポリシーをご確認ください。',
        updates: 'ポリシーの更新',
        updatesContent: '当社はこのCookieポリシーを随時更新する場合があります。変更を確認するには、このページを定期的にご確認ください。',
        contact: 'お問い合わせ',
        contactContent: 'Cookieの使用についてご質問がございましたら、お問い合わせページから当社までご連絡ください。',
      },
      contact: {
        title: 'お問い合わせ',
        lastUpdated: '最終更新：2025年1月1日',
        introduction: '当社は、キラー数独スコアに関するお客様のフィードバック、ご質問、ご提案を歓迎いたします。',
        waysToContact: 'お問い合わせ方法',
        email: 'メール',
        emailContent: '一般的なお問い合わせ、技術サポート、またはフィードバックについては、メールをお送りください。',
        github: 'GitHub',
        githubContent: '技術的な問題、バグレポート、または機能リクエストについては、当社のGitHubリポジトリをご訪問ください。',
        responseTime: '応答時間',
        responseTimeContent: '当社は営業日48時間以内にすべてのお問い合わせに応答することを目標としています。',
        typesOfInquiries: '対応するお問い合わせの種類',
        technicalSupport: '技術サポート',
        technicalSupportContent: 'ゲーム機能の問題、ブラウザ互換性、またはパフォーマンスの問題。',
        privacyConcerns: 'プライバシーの懸念',
        privacyConcernsContent: 'データ収集、使用、またはプライバシーポリシーに関するご質問。',
        featureRequests: '機能リクエスト',
        featureRequestsContent: '新機能や既存機能の改善に関するご提案。',
        bugReports: 'バグレポート',
        bugReportsContent: 'ゲームのエラー、不具合、または予期しない動作の報告。',
        feedback: '一般的なフィードバック',
        feedbackContent: 'ゲーム体験に関するコメント、ご提案、または一般的なフィードバック。',
        beforeContacting: 'お問い合わせ前に',
        beforeContactingContent: 'FAQセクションをご確認いただき、最新バージョンのブラウザをご使用いただいていることを確認してください。多くの問題は、ブラウザキャッシュをクリアするか、ブラウザを更新することで解決できます。',
        privacyNote: 'プライバシーに関する注意事項',
        privacyNoteContent: 'お問い合わせの際は、必要でない限り機密性の高い個人情報を含めないでください。当社はお客様の情報をお問い合わせへの応答目的でのみ使用します。',
        businessHours: '営業時間',
        businessHoursContent: '当社は通常、月曜日から金曜日の午前9時から午後5時（UTC）にお問い合わせに応答します。',
      },
    },
  },
};

export const useLanguage = () => {
  // 初始化語言 - 直接從localStorage讀取，避免useEffect延遲
  const getInitialLanguage = (): Language => {
    const savedLanguage = localStorage.getItem('killer-sudoku-language') as Language;
    if (savedLanguage && ['en', 'zh', 'ko', 'ja'].includes(savedLanguage)) {
      return savedLanguage;
    }

    // 如果沒有保存的語言，根據瀏覽器語言檢測
    const browserLang = navigator.language.toLowerCase();
    if (browserLang.startsWith('zh')) return 'zh';
    if (browserLang.startsWith('ko')) return 'ko';
    if (browserLang.startsWith('ja')) return 'ja';

    return 'en';
  };

  const [language, setLanguage] = useState<Language>(getInitialLanguage);

  useEffect(() => {
    // 監聽語言變更事件
    const handleLanguageChange = (event: CustomEvent) => {
      setLanguage(event.detail.language);
    };

    window.addEventListener('languageChange', handleLanguageChange as EventListener);

    return () => {
      window.removeEventListener('languageChange', handleLanguageChange as EventListener);
    };
  }, []);

  const t = (key: keyof typeof translations.en | string) => {
    // 支援嵌套鍵值，如 'legal.privacyPolicy.title'
    if (typeof key === 'string' && key.includes('.')) {
      const keys = key.split('.');
      let value: any = translations[language];

      for (const k of keys) {
        if (value && typeof value === 'object' && k in value) {
          value = value[k];
        } else {
          // 如果找不到，回退到英文
          value = translations.en;
          for (const fallbackKey of keys) {
            if (value && typeof value === 'object' && fallbackKey in value) {
              value = value[fallbackKey];
            } else {
              return key; // 如果都找不到，返回原始鍵值
            }
          }
          break;
        }
      }

      return typeof value === 'string' ? value : key;
    }

    // 原有的單層鍵值處理
    return translations[language][key as keyof typeof translations.en] || translations.en[key as keyof typeof translations.en] || key;
  };

  return { language, t };
};
